import { useEffect, useState } from 'react';
import { Check, ChevronDown, FileText, Landmark, Mail, MapPin, PenLine, Scale, ShieldCheck } from 'lucide-react';
import { capeLegalConcept } from '../data/siteContent';
import Reveal from '../components/Reveal';
import BackToConceptsButton from '../components/BackToConceptsButton';

export default function CapeLegalConcept({ onBack }) {
  const [area, setArea] = useState(capeLegalConcept.practiceAreas[0]);
  const [matterType, setMatterType] = useState('');
  const [openFaq, setOpenFaq] = useState(0);
  const [sent, setSent] = useState(false);
  useEffect(() => { window.scrollTo({ top: 0, left: 0, behavior: 'auto' }); }, []);
  const scrollTo = (id) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
  const enquireAbout = (title = '') => { setMatterType(title); scrollTo('capelegal-enquiry'); };
  const portfolioEnquiry = () => {
    window.sessionStorage.setItem('prefillWebsiteType', 'Professional Services Website');
    window.sessionStorage.setItem('prefillProjectMessage', 'I want to use the CapeLegal Advisory style for my professional service business.');
    onBack?.(); window.setTimeout(() => scrollTo('contact'), 120);
  };
  const submit = (e) => { e.preventDefault(); setSent(true); };
  return <div className="capelegal-page min-h-screen overflow-x-hidden bg-[#08111b] text-[#f7f1e4]">
    <BackToConceptsButton onBack={onBack} />
    <header className="sticky top-0 z-40 border-b border-[#c7a76a]/15 bg-[#08111b]/88 px-4 py-3 backdrop-blur-xl sm:px-5"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3"><button onClick={onBack} className="capelegal-link rounded-full border border-white/15 px-4 py-2 text-sm">← Back to Concepts</button><button onClick={portfolioEnquiry} className="capelegal-btn rounded-full border border-[#c7a76a]/40 bg-[#c7a76a] px-5 py-2.5 text-sm font-semibold text-[#08111b]">Use this style for my professional service business</button></div></header>
    <section className="relative isolate overflow-hidden px-4 py-16 sm:px-5 lg:min-h-[92vh] lg:py-24"><img src={capeLegalConcept.images.hero.src} alt={capeLegalConcept.images.hero.alt} className="absolute inset-0 -z-30 h-full w-full object-cover opacity-25"/><div className="capelegal-paper absolute inset-0 -z-20"/><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,#08111b_10%,rgba(8,17,27,.92),rgba(8,17,27,.65))]"/><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1fr_.82fr]"><Reveal><p className="mb-5 inline-flex rounded-full border border-[#c7a76a]/25 bg-[#c7a76a]/10 px-4 py-2 text-sm uppercase tracking-[.28em] text-[#dec894]">CapeLegal Advisory · Cape Town</p><h1 className="capelegal-heading max-w-4xl text-5xl font-semibold leading-[1.02] tracking-[-.045em] sm:text-7xl">Clear advice for complex decisions.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#d8d0c1] sm:text-xl">Boutique legal and business advisory for contracts, compliance, property, company matters and professional decision-making.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={()=>enquireAbout()} className="capelegal-btn rounded-full bg-[#c7a76a] px-7 py-4 font-semibold text-[#08111b]">Request a Consultation</button><button onClick={()=>scrollTo('capelegal-areas')} className="capelegal-link rounded-full border border-white/15 bg-white/5 px-7 py-4 font-semibold">Explore Advisory Areas</button></div><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{capeLegalConcept.trustBadges.map(b=><span key={b} className="rounded-2xl border border-white/10 bg-white/[.07] p-3 text-sm text-[#efe3cb] backdrop-blur">{b}</span>)}</div></Reveal><Reveal delay={0.08}><HeroStack enquire={()=>enquireAbout()} /></Reveal></div></section>
    <main>
      <Notice />
      <Section><div className="grid gap-4 sm:grid-cols-4">{capeLegalConcept.stats.map((s,i)=><Reveal key={s.label} delay={i*.04}><div className="rounded-[2rem] border border-[#c7a76a]/18 bg-[#f6ecd9]/[.06] p-6"><p className="text-4xl font-semibold text-[#dec894]">{s.value}</p><p className="mt-2 text-sm uppercase tracking-[.18em] text-[#cfc5b2]">{s.label}</p></div></Reveal>)}</div></Section>
      <Section><div className="grid gap-8 lg:grid-cols-[1fr_.9fr] lg:items-center"><div><Intro eyebrow="Firm positioning" title="Calm, structured guidance for important decisions." text="CapeLegal Advisory is built around calm, practical guidance for people and businesses facing important decisions. The focus is clarity: understanding the issue, identifying the risks and outlining the next step in plain language."/><div className="grid gap-3 sm:grid-cols-2">{capeLegalConcept.highlights.map(h=><p key={h} className="rounded-2xl border border-white/10 bg-white/[.05] p-4"><Check className="mb-2 text-[#dec894]"/> {h}</p>)}</div></div><DocumentVisual /></div></Section>
      <Section id="capelegal-areas" className="bg-[#0d1824]"><Intro eyebrow="Advisory areas" title="Case-file selector for advisory services." text="Select a practice area to reveal who it helps, typical matters and documents involved."/><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-2">{capeLegalConcept.practiceAreas.map(p=><button key={p.title} onClick={()=>setArea(p)} className={`case-tab text-left ${area.title===p.title?'is-active':''}`}><FileText size={18}/><span>{p.title}</span></button>)}</div><article className="rounded-[2.25rem] border border-[#c7a76a]/25 bg-[#f6ecd9]/[.07] p-6 shadow-2xl"><p className="text-sm uppercase tracking-[.24em] text-[#dec894]">Advisory file</p><h3 className="mt-3 text-4xl font-semibold">{area.title}</h3><p className="mt-4 leading-8 text-[#d8d0c1]">{area.description}</p>{[['Who it helps',area.helps],['Typical matters',area.matters],['Documents involved',area.documents]].map(([l,t])=><p key={l} className="mt-4 leading-7"><b className="text-[#dec894]">{l}:</b> {t}</p>)}<button onClick={()=>enquireAbout(area.title)} className="capelegal-btn mt-6 rounded-full border border-[#c7a76a]/40 px-6 py-3 font-semibold text-[#dec894]">Enquire About This</button></article></div></Section>
      <Section><Intro eyebrow="Consultation process" title="A clear path from enquiry to next step." text="A reassuring five-step flow helps clients understand what happens before any work begins."/><div className="consult-line grid gap-4 lg:grid-cols-5">{capeLegalConcept.process.map((p,i)=><article key={p.title} className="relative rounded-[2rem] border border-white/10 bg-white/[.05] p-5"><span className="grid h-11 w-11 place-items-center rounded-full bg-[#dec894] font-semibold text-[#08111b]">{i+1}</span><h3 className="mt-5 text-xl font-semibold">{p.title}</h3><p className="mt-2 text-[#cfc5b2]">{p.text}</p></article>)}</div></Section>
      <Section className="bg-[#0d1824]"><Intro eyebrow="Advisors" title="Advisor profiles with calm professional portraits." text="Advisor profiles and credentials are illustrative examples for this concept."/><div className="grid gap-5 lg:grid-cols-3">{capeLegalConcept.advisors.map(a=><article key={a.name} className="advisor-card overflow-hidden rounded-[2rem] border border-white/10 bg-white/[.05]"><div className="aspect-[4/5] overflow-hidden bg-[#0d1824]"><img src={a.image} alt={a.alt} loading="lazy" decoding="async" className="h-full w-full object-cover object-[center_18%]"/></div><div className="p-6"><h3 className="text-2xl font-semibold">{a.name}</h3><p className="text-[#dec894]">{a.role}</p><p className="mt-3 text-[#cfc5b2]">{a.bio}</p><div className="advisor-reveal mt-4 rounded-2xl border border-[#c7a76a]/20 bg-[#c7a76a]/10 p-4"><b>Advisory focus:</b> {a.focus}<br/><span className="text-sm">{a.credentials}</span></div></div></article>)}</div></Section>
      <CardsSection />
      <Section className="bg-[#0d1824]"><Intro eyebrow="Resources" title="Insight cards for professional advisory websites." text="Static article cards show how a resource section can build trust with clear, helpful insights."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{capeLegalConcept.resources.map(r=><article key={r.title} className="rounded-[2rem] border border-white/10 bg-white/[.05] p-5"><p className="text-sm uppercase tracking-[.2em] text-[#dec894]">{r.category}</p><h3 className="mt-4 text-xl font-semibold">{r.title}</h3><p className="mt-3 text-[#cfc5b2]">{r.excerpt}</p><p className="mt-5 text-sm text-[#dec894]">{r.time} · Read Insight</p></article>)}</div></Section>
      <Enquiry matterType={matterType} setMatterType={setMatterType} submit={submit} sent={sent}/>
      <ContactOffice enquire={enquireAbout} portfolioEnquiry={portfolioEnquiry}/>
      <Section><Intro eyebrow="Testimonials" title="Realistic feedback without outcome claims." text="Example testimonials demonstrate calm, credible social proof."/><div className="grid gap-5 lg:grid-cols-3">{capeLegalConcept.testimonials.map(t=><article key={t.name} className="rounded-[2rem] border border-white/10 bg-white/[.05] p-6"><p className="leading-8 text-[#efe3cb]">“{t.text}”</p><p className="mt-5 font-semibold">{t.name}</p><p className="text-[#dec894]">{t.type}</p></article>)}</div></Section>
      <Section className="bg-[#0d1824]"><Intro eyebrow="FAQ" title="Professional advisory questions." text="An accessible accordion keeps detailed answers tidy on mobile."/>{capeLegalConcept.faqs.map((f,i)=><div key={f.question} className="border-t border-white/10 py-2"><button onClick={()=>setOpenFaq(openFaq===i?-1:i)} className="flex w-full items-center justify-between gap-4 py-4 text-left text-lg font-semibold"><span>{f.question}</span><ChevronDown className={`shrink-0 transition ${openFaq===i?'rotate-180':''}`}/></button>{openFaq===i && <p className="pb-4 leading-7 text-[#cfc5b2]">{f.answer}</p>}</div>)}</Section>
      <Section><div className="rounded-[2.5rem] border border-[#c7a76a]/25 bg-[#f6ecd9] p-8 text-center text-[#08111b] sm:p-12"><Landmark className="mx-auto"/><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Need clarity before your next decision?</h2><p className="mx-auto mt-5 max-w-2xl text-lg">Send a confidential enquiry and receive structured guidance on the next step.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><button onClick={()=>enquireAbout()} className="rounded-full bg-[#08111b] px-7 py-4 font-semibold text-white">Request a Consultation</button><button onClick={()=>scrollTo('capelegal-areas')} className="rounded-full border border-[#08111b]/20 px-7 py-4 font-semibold">Explore Advisory Areas</button><button onClick={()=>scrollTo('capelegal-contact')} className="rounded-full border border-[#08111b]/20 px-7 py-4 font-semibold">Contact the Team</button></div><button onClick={portfolioEnquiry} className="mt-5 rounded-full bg-white px-7 py-4 font-semibold">Use this style for my professional service business</button></div></Section>
      <Notice disclaimer />
    </main>
  </div>;
}
function HeroStack({enquire}){return <div className="relative min-h-[520px]"><div className="doc-card doc-1"><FileText/><h3>Contract review</h3><p>Obligations · risks · next steps</p></div><div className="doc-card doc-2"><Scale/><h3>Compliance note</h3><p>Scope before work begins</p></div><div className="doc-card doc-3"><PenLine/><h3>Confidential enquiry</h3><label>Matter type<select><option>Contract Review</option></select></label><label>Urgency<select><option>This week</option></select></label><label>Preferred contact<select><option>Email</option></select></label><button onClick={enquire}>Start Enquiry</button></div></div>}
function DocumentVisual(){return <div className="relative"><img src={capeLegalConcept.images.intro.src} alt={capeLegalConcept.images.intro.alt} loading="lazy" decoding="async" className="h-[34rem] w-full rounded-[2.5rem] object-cover opacity-85"/><div className="absolute -bottom-6 left-6 right-6 rounded-[2rem] border border-[#c7a76a]/25 bg-[#08111b]/90 p-5 backdrop-blur"><p className="text-[#dec894]">Matter note</p><p className="mt-2 text-[#efe3cb]">Issue → risk → documents → practical next step.</p></div></div>}
function CardsSection(){return <Section><Intro eyebrow="Trust and discretion" title="Designed around clarity, discretion and trust." text="Premium professional-service sites need credible detail, careful language and practical reassurance."/><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{capeLegalConcept.trustCards.map(c=><article key={c} className="rounded-[2rem] border border-white/10 bg-white/[.05] p-5"><ShieldCheck className="text-[#dec894]"/><h3 className="mt-4 font-semibold">{c}</h3></article>)}</div><div className="mt-8 flex flex-wrap gap-3">{capeLegalConcept.trustSeals.map(s=><span key={s} className="rounded-full border border-[#c7a76a]/25 bg-[#c7a76a]/10 px-4 py-2 text-sm text-[#dec894]">{s}</span>)}</div></Section>}
function Enquiry({matterType,setMatterType,submit,sent}){return <Section id="capelegal-enquiry" className="bg-[#0d1824]"><div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><Intro eyebrow="Confidential consultation" title="A refined intake card for serious enquiries." text="This is a concept enquiry form showing how consultation requests could be structured."/><form onSubmit={submit} name="project-enquiry" method="POST" action="/" data-netlify="true" className="rounded-[2rem] border border-[#c7a76a]/20 bg-white/[.06] p-5 sm:p-6"><input type="hidden" name="form-name" value="project-enquiry"/><input type="hidden" name="websiteType" value="Professional Services Website"/><input type="hidden" name="budget" value="Example consultation enquiry"/><input type="hidden" name="business" value="CapeLegal Advisory concept"/>{sent&&<p role="status" className="mb-5 rounded-2xl border border-[#c7a76a]/30 bg-[#c7a76a]/10 p-4 text-[#dec894]">Example success message: enquiry details received for review.</p>}<div className="grid gap-4 md:grid-cols-2"><Field label="Name" name="name"/><Field label="Email" name="email" type="email"/><Field label="Phone / WhatsApp" name="phone"/><Field label="Company name, optional" name="company"/><Field label="Matter type"><select name="matterType" value={matterType} onChange={e=>setMatterType(e.target.value)} className="cape-input"><option value="">Select matter type</option>{capeLegalConcept.practiceAreas.map(p=><option key={p.title}>{p.title}</option>)}</select></Field><Field label="Urgency"><select name="urgency" className="cape-input"><option>This week</option><option>This month</option><option>Planning ahead</option></select></Field><Field label="Preferred contact method"><select name="contactMethod" className="cape-input"><option>Email</option><option>Phone</option><option>WhatsApp</option></select></Field><Field label="Do you have documents to review?"><select name="documents" className="cape-input"><option>Yes</option><option>No</option><option>Not sure</option></select></Field></div><label className="mt-4 block text-sm font-medium text-[#d8d0c1]">Short summary of matter<textarea name="message" rows="5" className="cape-input mt-2 min-h-32" defaultValue="CapeLegal Advisory concept — example consultation enquiry."/></label><label className="mt-4 flex gap-3 text-sm text-[#d8d0c1]"><input required type="checkbox" className="mt-1"/>I understand this is a concept enquiry example and that submitting this form does not create a legal advisor/client relationship.</label><button className="capelegal-btn mt-5 rounded-full bg-[#c7a76a] px-7 py-4 font-semibold text-[#08111b]">Send Consultation Enquiry</button><p className="mt-4 text-sm text-[#a99f8d]">Information on this concept website is illustrative only and does not constitute legal advice. No attorney-client relationship is created.</p></form></div></Section>}
function ContactOffice({enquire, portfolioEnquiry}){return <Section id="capelegal-contact"><div className="grid gap-8 lg:grid-cols-2"><div><Intro eyebrow="Contact" title="Cape Town office details." text="By appointment only, with remote consultations available in this concept."/><div className="space-y-3 text-[#d8d0c1]"><p><MapPin className="mr-2 inline text-[#dec894]"/>Cape Town, South Africa · By appointment only</p><p>Illustrative contact area shown for concept layout only.</p><p><Mail className="mr-2 inline text-[#dec894]"/>Illustrative email area shown for concept layout only.</p></div><div className="mt-6 flex flex-wrap gap-3"><button onClick={()=>enquire()} className="capelegal-btn rounded-full bg-[#c7a76a] px-6 py-3 font-semibold text-[#08111b]">Request Consultation</button><button onClick={portfolioEnquiry} className="capelegal-link rounded-full border border-white/15 px-6 py-3">Discuss This Website Style</button><a className="capelegal-link rounded-full border border-white/15 px-6 py-3" href="https://maps.google.com/?q=Cape+Town+South+Africa">Get Directions</a></div></div><div className="rounded-[2rem] border border-white/10 bg-white/[.05] p-6"><h3 className="text-2xl font-semibold">Office hours</h3>{capeLegalConcept.hours.map(([d,h])=><p key={d} className="flex justify-between border-b border-white/10 py-3"><span>{d}</span><span className="text-[#dec894]">{h}</span></p>)}<div className="mt-6 rounded-2xl border border-[#c7a76a]/20 bg-[#c7a76a]/10 p-5 text-[#dec894]">Styled map area · Cape Town professional district</div></div></div></Section>}
function Notice({disclaimer=false}){return <section className="px-4 py-6 sm:px-5"><div className="mx-auto max-w-7xl rounded-2xl border border-[#c7a76a]/20 bg-[#c7a76a]/10 p-4 text-sm leading-7 text-[#efe3cb]">{disclaimer ? 'Information shown on this concept website is illustrative only and does not constitute legal advice. No attorney-client relationship is created.' : 'This concept website shows how a business in this industry could be presented online. Images, prices, services, reviews and business details are illustrative.'}</div></section>}
function Section({children,id,className=''}){return <section id={id} className={`px-4 py-20 sm:px-5 ${className}`}><div className="mx-auto max-w-7xl">{children}</div></section>}
function Intro({eyebrow,title,text}){return <div className="mb-10 max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[.25em] text-[#dec894]">{eyebrow}</p><h2 className="capelegal-heading mt-3 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">{title}</h2><p className="mt-4 text-lg leading-8 text-[#cfc5b2]">{text}</p></div>}
function Field({label,name,type='text',children}){return <label className="block text-sm font-medium text-[#d8d0c1]">{label}{children || <input name={name} type={type} className="cape-input mt-2"/>}</label>}
