import { useEffect, useState } from 'react';
import { Check, ChevronDown, Dumbbell, Flame, Goal, LineChart, ShieldCheck, Star, Trophy, Utensils } from 'lucide-react';
import { fitFormConcept } from '../data/siteContent';
import Reveal from '../components/Reveal';

const stats = [['300+', 'coaching sessions'], ['92%', 'client consistency rate'], ['12', 'week transformation blocks'], ['1:1', 'support']];
const journey = [['Week 1', 'Assessment and goal setting'], ['Weeks 2–4', 'Build the base'], ['Weeks 5–8', 'Progressive overload and habit consistency'], ['Weeks 9–11', 'Push phase and refinement'], ['Week 12', 'Review, retest and next plan']];
const metrics = ['Workouts completed', 'Weekly consistency', 'Steps', 'Strength progress', 'Body measurements', 'Protein target', 'Sleep/recovery', 'Check-in notes'];
const testimonials = [
  ['Megan R.', 'Fat-loss client', 'I finally stopped guessing what to do in the gym. The plan gave me structure and the weekly check-ins kept me consistent.'],
  ['Jason K.', 'Strength client', 'The loading plan made progress easy to track. I felt stronger without burning out or chasing random workouts.'],
  ['Leah S.', 'Busy professional', 'The habits were realistic for my schedule. Online support made it feel personal even when I trained after work.'],
];
const packages = [
  ['Starter Plan', 'Best for clients who want structure', ['Training plan', 'Basic habit targets', 'Monthly check-in'], 'From R650/month'],
  ['Coaching Plus', 'Most Popular', ['Training plan', 'Nutrition guidance', 'Weekly check-ins', 'Progress tracking', 'WhatsApp support'], 'From R950/month'],
  ['Premium 1:1 Coaching', 'Personalised support', ['Custom programming', 'Technique feedback', 'Weekly reviews', 'Priority support'], 'From R1,800/month'],
];
const transformations = [
  ['Megan R.', 'Fat loss and strength', '12 weeks', 'Improved consistency, stronger lifts, better nutrition structure', ['10/12 weeks completed', '+35 kg leg press progress', '8 cm waist reduction example']],
  ['Sipho M.', 'Strength progress', '8 weeks', 'Built confidence with progressive loading and clearer technique cues', ['+20 kg deadlift progress', '16 sessions completed', 'Technique confidence improved']],
  ['Ava T.', 'Beginner confidence', '12 weeks', 'Moved from inconsistent workouts to a repeatable weekly routine', ['3 workouts/week average', '7,000 step habit', 'First gym programme completed']],
];

export default function FitFormConcept({ onBack }) {
  const [goal, setGoal] = useState(fitFormConcept.goals[0]);
  const [programme, setProgramme] = useState(null);
  const [openFaq, setOpenFaq] = useState(0);
  const [transformView, setTransformView] = useState('after');
  const [mainGoal, setMainGoal] = useState('');
  useEffect(() => { window.scrollTo({ top: 0, left: 0, behavior: 'auto' }); }, []);
  const scrollTo = (id) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
  const startGoal = (title = '') => { setMainGoal(title); scrollTo('fitform-enquiry'); };
  const clientEnquiry = () => { window.sessionStorage.setItem('prefillWebsiteType', 'Fitness Coach Website'); window.sessionStorage.setItem('prefillProjectMessage', 'I want a premium fitness coaching website in the FitForm style.'); onBack?.(); window.setTimeout(() => scrollTo('contact'), 120); };

  return <div className="fitform-page min-h-screen overflow-x-hidden bg-[#07090b] text-[#f7fbff]">
    <header className="sticky top-0 z-40 border-b border-lime-300/10 bg-[#07090b]/85 px-4 py-3 backdrop-blur-xl sm:px-5"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3"><button onClick={onBack} className="rounded-full border border-white/15 px-4 py-2 text-sm hover:bg-white/10">← Back to portfolio</button><button onClick={clientEnquiry} className="fitform-btn rounded-full bg-lime-300 px-5 py-2.5 text-sm font-black text-[#071008]">Use this style for my fitness business</button></div></header>
    <section className="relative isolate overflow-hidden px-4 py-16 sm:px-5 lg:min-h-[92vh] lg:py-24"><img src={fitFormConcept.images.hero.src} alt={fitFormConcept.images.hero.alt} className="absolute inset-0 -z-20 h-full w-full object-cover opacity-35"/><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_20%_20%,rgba(190,255,41,.24),transparent_24rem),radial-gradient(circle_at_82%_30%,rgba(37,99,235,.32),transparent_22rem),linear-gradient(90deg,#07090b_8%,rgba(7,9,11,.82),rgba(7,9,11,.55))]"/><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1fr_.82fr]"><Reveal><p className="mb-5 inline-flex rounded-full border border-lime-300/25 bg-lime-300/10 px-4 py-2 text-sm uppercase tracking-[.26em] text-lime-200">FitForm Coaching · Cape Town</p><h1 className="text-4xl font-black uppercase leading-[.92] tracking-[-.06em] sm:text-6xl lg:text-8xl">Train smarter. Move stronger. Become consistent.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-200 sm:text-xl">Personal training and online coaching built around strength, structure, accountability and real-life progress.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={()=>startGoal()} className="fitform-btn rounded-full bg-lime-300 px-7 py-4 font-black text-[#071008]">Start Coaching</button><button onClick={()=>scrollTo('fitform-programmes')} className="rounded-full border border-white/15 bg-white/10 px-7 py-4 font-bold hover:bg-white/15">Explore Programmes</button></div><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{fitFormConcept.trustBadges.map(b=><span key={b} className="rounded-2xl border border-white/10 bg-white/10 p-3 text-sm backdrop-blur">{b}</span>)}</div></Reveal><Reveal delay={0.08}><Dashboard /></Reveal></div></section>
    <main>
      <Section><div className="grid gap-4 sm:grid-cols-4">{stats.map(([n,l],i)=><Reveal key={l} delay={i*.04}><div className="rounded-[2rem] border border-white/10 bg-white/[.06] p-6"><p className="text-4xl font-black text-lime-300">{n}</p><p className="mt-2 text-sm uppercase tracking-[.18em] text-slate-300">{l}</p></div></Reveal>)}</div></Section>
      <Section id="fitform-goals"><Intro eyebrow="Choose your goal" title="Pick the outcome. FitForm shapes the plan." text="Interactive goal tabs make the coaching path feel personal before a visitor fills in the form."/><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3">{fitFormConcept.goals.map(g=><button key={g.title} onClick={()=>setGoal(g)} className={`rounded-2xl border p-4 text-left font-black transition ${goal.title===g.title?'border-lime-300 bg-lime-300 text-[#071008]':'border-white/10 bg-white/[.06] hover:border-lime-300/50'}`}>{g.title}</button>)}</div><article className="rounded-[2rem] border border-lime-300/20 bg-gradient-to-br from-white/[.09] to-blue-500/10 p-6"><Goal className="text-lime-300"/><h3 className="mt-4 text-4xl font-black uppercase">{goal.title}</h3><Info label="Who it is for" text={goal.for}/><Info label="Coaching focus" text={goal.focus}/><Info label="Example weekly structure" text={goal.structure}/><button onClick={()=>startGoal(goal.title)} className="fitform-btn mt-6 rounded-full bg-lime-300 px-6 py-3 font-black text-[#071008]">Start With This Goal</button></article></div></Section>
      <Section id="fitform-programmes" className="bg-[#0d1117]"><Intro eyebrow="Programmes" title="Workout-style cards with reveal details." text="Tap or hover a card to reveal what clients get inside each offer."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{fitFormConcept.programmes.map(p=><ProgramCard key={p.title} p={p} active={programme===p.title} setActive={setProgramme} enquire={()=>startGoal(p.title)}/>)}</div></Section>
      <Section><Intro eyebrow="12-week journey" title="A clear training block from assessment to next plan." text="A timeline helps clients understand progress, checkpoints and momentum."/><div className="relative grid gap-4 lg:grid-cols-5"><div className="absolute left-0 top-8 hidden h-1 w-full bg-gradient-to-r from-lime-300 via-blue-500 to-lime-300 lg:block"/>{journey.map(([w,t],i)=><Reveal key={w} delay={i*.05}><article className="relative rounded-[2rem] border border-white/10 bg-[#111821] p-5"><span className="grid h-12 w-12 place-items-center rounded-full bg-lime-300 font-black text-[#071008]">{i+1}</span><h3 className="mt-5 text-xl font-black">{w}</h3><p className="mt-2 text-slate-300">{t}</p></article></Reveal>)}</div></Section>
      <Section className="bg-[#0d1117]"><div className="grid gap-8 lg:grid-cols-[.78fr_1.22fr] lg:items-center"><img src={fitFormConcept.images.coach.src} alt={fitFormConcept.images.coach.alt} loading="lazy" decoding="async" className="h-[34rem] w-full rounded-[2.5rem] object-cover"/><div><Intro eyebrow="Coach profile" title="Connor Blake — Strength & Body Composition Coach" text="Connor helps everyday clients build strength, improve body composition and create training routines they can actually stick to. His coaching style combines structure, accountability and realistic progress."/><div className="grid gap-3 sm:grid-cols-2">{['Strength training','Muscle building','Fat-loss coaching','Habit tracking','Beginner confidence','Online coaching','Evidence-informed coaching','Progress-based programming','Technique focused','Sustainable nutrition habits'].map(x=><span key={x} className="rounded-2xl border border-white/10 bg-white/[.06] p-4"><ShieldCheck className="mb-2 text-lime-300"/> {x}</span>)}</div></div></div></Section>
      <Section><Intro eyebrow="Transformations" title="Example client journeys without unrealistic claims." text="A simple before/after toggle keeps results interactive while staying honest."/><div className="mb-5 flex gap-2"><button onClick={()=>setTransformView('before')} className={`rounded-full px-5 py-3 font-black ${transformView==='before'?'bg-lime-300 text-[#071008]':'bg-white/10'}`}>Before</button><button onClick={()=>setTransformView('after')} className={`rounded-full px-5 py-3 font-black ${transformView==='after'?'bg-lime-300 text-[#071008]':'bg-white/10'}`}>After</button></div><div className="grid gap-5 lg:grid-cols-3">{transformations.map(t=><article key={t[0]} className="rounded-[2rem] border border-white/10 bg-white/[.06] p-5"><div className="rounded-[1.5rem] bg-gradient-to-br from-slate-800 to-blue-900 p-5"><p className="text-sm uppercase tracking-[.2em] text-lime-300">{transformView} snapshot</p><p className="mt-5 text-3xl font-black">{transformView==='before'?'Getting started':'Progress tracked'}</p></div><h3 className="mt-5 text-2xl font-black">{t[0]}</h3><p className="text-lime-300">Goal: {t[1]} · {t[2]}</p><p className="mt-3 text-slate-300">{t[3]}</p><ul className="mt-4 space-y-2">{t[4].map(m=><li key={m} className="flex gap-2"><Check className="text-lime-300"/> {m}</li>)}</ul><p className="mt-4 italic text-slate-300">“The plan made the next step clear every week.”</p></article>)}</div><p className="mt-5 text-sm text-slate-400">Results vary by client. Example transformations are shown for example layout.</p></Section>
      <Section className="bg-[#0d1117]"><Intro eyebrow="Client dashboard" title="Track the habits that make progress visible." text="Visual-only app-style metric cards show how coaching can feel structured and modern."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{metrics.map((m,i)=><div key={m} className="rounded-[2rem] border border-white/10 bg-white/[.06] p-5"><LineChart className="text-lime-300"/><p className="mt-4 font-black">{m}</p><div className="mt-4 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-lime-300 to-blue-500" style={{width:`${55+i*5}%`}}/></div></div>)}</div></Section>
      <Section><div className="grid gap-8 lg:grid-cols-2"><div><Intro eyebrow="Nutrition & habits" title="Practical support without extreme dieting." text="Protein targets, meal structure, hydration, step goals, sleep, recovery, weekly check-ins and flexible lifestyle habits."/><img src={fitFormConcept.images.nutrition.src} alt={fitFormConcept.images.nutrition.alt} loading="lazy" decoding="async" className="h-72 w-full rounded-[2rem] object-cover"/></div><aside className="rounded-[2rem] border border-lime-300/20 bg-lime-300 p-6 text-[#071008]"><h3 className="text-3xl font-black">Sample day of habits</h3>{['7,000 steps','120 g protein','2 L water','Training session','7+ hours sleep','Check-in completed'].map(x=><p key={x} className="mt-4 flex items-center gap-3 rounded-2xl bg-black/10 p-4 font-bold"><Check/> {x}</p>)}</aside></div></Section>
      <Section className="bg-[#0d1117]"><Intro eyebrow="Reviews" title="Social proof for different coaching goals." text="Realistic testimonial patterns for fat-loss clients, strength clients and busy professionals."/><div className="grid gap-5 lg:grid-cols-3">{testimonials.map(([n,g,r])=><article key={n} className="rounded-[2rem] border border-white/10 bg-white/[.06] p-6"><div className="flex text-lime-300">{Array.from({length:5}).map((_,i)=><Star key={i} fill="currentColor" size={18}/>)}</div><p className="mt-5 leading-8 text-slate-200">“{r}”</p><p className="mt-5 font-black">{n}</p><p className="text-lime-300">{g}</p></article>)}</div></Section>
      <Section><Intro eyebrow="Packages" title="Simple pricing cards for fast decisions." text="Example pricing shown for example layout. Real pricing can be customised."/><div className="grid gap-5 lg:grid-cols-3">{packages.map(([n,b,fs,price])=><article key={n} className={`rounded-[2rem] border p-6 ${b==='Most Popular'?'border-lime-300 bg-lime-300 text-[#071008]':'border-white/10 bg-white/[.06]'}`}><p className="font-black uppercase tracking-[.18em]">{b}</p><h3 className="mt-4 text-3xl font-black">{n}</h3><ul className="mt-5 space-y-3">{fs.map(f=><li key={f} className="flex gap-2"><Check/> {f}</li>)}</ul><p className="mt-6 text-2xl font-black">{price}</p><button onClick={()=>startGoal(n)} className="mt-5 rounded-full bg-[#071008] px-5 py-3 font-black text-white">Enquire</button></article>)}</div></Section>
      <Enquiry mainGoal={mainGoal} setMainGoal={setMainGoal}/>
      <Section><Intro eyebrow="FAQ" title="Fitness-coaching questions before clients enquire." text="An accordion keeps deeper answers tidy on mobile."/>{fitFormConcept.faqs.map((f,i)=><div key={f.question} className="border-t border-white/10 py-2"><button onClick={()=>setOpenFaq(openFaq===i?-1:i)} className="flex w-full items-center justify-between gap-4 py-4 text-left font-black"><span>{f.question}</span><ChevronDown className={`shrink-0 transition ${openFaq===i?'rotate-180':''}`}/></button>{openFaq===i && <p className="pb-4 leading-7 text-slate-300">{f.answer}</p>}</div>)}</Section>
      <Section><div className="rounded-[2.5rem] bg-gradient-to-br from-lime-300 to-blue-500 p-8 text-center text-[#071008] sm:p-12"><Trophy className="mx-auto"/><h2 className="mt-4 text-4xl font-black uppercase sm:text-5xl tracking-[-.05em]">Ready to stop guessing and start progressing?</h2><p className="mx-auto mt-5 max-w-2xl text-lg font-semibold">Choose your goal, send your details and we’ll build a coaching path around your life.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><button onClick={()=>startGoal()} className="rounded-full bg-[#071008] px-7 py-4 font-black text-white">Start Coaching</button><button onClick={()=>scrollTo('fitform-goals')} className="rounded-full border border-[#071008]/20 px-7 py-4 font-black">Choose My Goal</button><button onClick={()=>scrollTo('fitform-programmes')} className="rounded-full border border-[#071008]/20 px-7 py-4 font-black">View Programmes</button></div><button onClick={clientEnquiry} className="mt-5 rounded-full bg-white px-7 py-4 font-black">Use this style for my fitness business</button><p className="mx-auto mt-6 max-w-3xl rounded-2xl bg-black/10 p-4 text-sm font-semibold">This concept website shows how a business in this industry could be presented online. Images, prices, services, reviews and business details are illustrative.</p></div></Section>
    </main><button onClick={()=>startGoal()} className="fixed bottom-4 left-4 right-4 z-40 rounded-full bg-lime-300 px-5 py-4 font-black text-[#071008] shadow-2xl sm:hidden">Start Coaching</button>
  </div>;
}
function Dashboard(){return <div className="relative rounded-[2.5rem] border border-white/10 bg-[#0d1117]/85 p-5 shadow-2xl backdrop-blur"><div className="flex items-center justify-between"><b>Weekly dashboard</b><span className="rounded-full bg-lime-300 px-3 py-1 text-xs font-black text-[#071008]">Example view</span></div><div className="mt-6 grid grid-cols-[.8fr_1fr] gap-5"><div className="grid place-items-center rounded-full border-[12px] border-lime-300/20 p-10 outline outline-[10px] outline-blue-500/10"><span className="text-5xl font-black text-lime-300">92%</span><small>Consistency</small></div><div className="space-y-3">{[['Workout streak','18 days',Flame],['Sessions completed','38',Dumbbell],['Calories/macros','2,150 kcal',Utensils]].map(([l,v,I])=><p key={l} className="flex items-center gap-3 rounded-2xl bg-white/10 p-3"><I className="text-lime-300"/><span><b>{v}</b><br/><small>{l}</small></span></p>)}</div></div><div className="mt-5 rounded-2xl bg-white/10 p-4"><div className="mb-2 flex justify-between text-sm"><span>Rep counter</span><b>12 / 15</b></div><div className="h-3 rounded-full bg-white/10"><div className="h-full w-4/5 rounded-full bg-gradient-to-r from-lime-300 to-blue-500"/></div></div></div>}
function Section({children,id,className=''}){return <section id={id} className={`px-4 py-20 sm:px-5 ${className}`}><div className="mx-auto max-w-7xl">{children}</div></section>}
function Intro({eyebrow,title,text}){return <div className="mb-10 max-w-3xl"><p className="text-sm font-black uppercase tracking-[.25em] text-lime-300">{eyebrow}</p><h2 className="mt-3 text-4xl font-black uppercase tracking-[-.05em] sm:text-5xl">{title}</h2><p className="mt-4 text-lg leading-8 text-slate-300">{text}</p></div>}
function Info({label,text}){return <p className="mt-4 leading-7 text-slate-200"><b className="text-lime-300">{label}:</b> {text}</p>}
function ProgramCard({p,active,setActive,enquire}){return <article onClick={()=>setActive(active?null:p.title)} className={`group cursor-pointer overflow-hidden rounded-[2rem] border p-4 transition ${p.popular?'border-lime-300 bg-lime-300/10':'border-white/10 bg-white/[.06]'} hover:-translate-y-1`}><img src={p.image} alt={`${p.title} fitness programme`} loading="lazy" decoding="async" className="h-44 w-full rounded-[1.5rem] object-cover"/><div className="mt-4 flex items-center justify-between gap-2"><h3 className="text-xl font-black">{p.title}</h3>{p.popular && <span className="rounded-full bg-lime-300 px-2 py-1 text-xs font-black text-[#071008]">Most Popular</span>}</div><p className="mt-2 text-sm text-lime-300">Best for {p.best}</p><p className="mt-3 text-slate-300">For: {p.for}</p><div className={`grid transition-all duration-500 ${active?'grid-rows-[1fr]':'grid-rows-[0fr] group-hover:grid-rows-[1fr]'}`}><div className="overflow-hidden"><p className="mt-4 font-black">What you get</p>{p.includes.map(x=><p key={x} className="mt-2 flex gap-2"><Check className="text-lime-300"/> {x}</p>)}</div></div><p className="mt-4 font-bold">{p.duration} · {p.price}</p><button onClick={(e)=>{e.stopPropagation(); enquire();}} className="mt-4 rounded-full border border-lime-300/40 px-4 py-2 font-black text-lime-300">Enquire</button></article>}
function Field({label,name,type='text',children,value,onChange}){return <label className="block text-sm font-bold text-slate-200">{label}{children || <input name={name} type={type} value={value} onChange={onChange} className="mt-2 min-h-[52px] w-full rounded-2xl border border-white/10 bg-white/10 p-4 text-white outline-none focus:border-lime-300"/>}</label>}
function Enquiry({mainGoal,setMainGoal}){return <Section id="fitform-enquiry" className="bg-[#0d1117]"><div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><Intro eyebrow="Coaching enquiry" title="Start with a focused sample lead flow." text="This is a concept enquiry form showing how coaching enquiries could be qualified."/><form name="project-enquiry" method="POST" action="/" data-netlify="true" className="rounded-[2rem] border border-white/10 bg-white/[.06] p-5 sm:p-6"><input type="hidden" name="form-name" value="project-enquiry"/><input type="hidden" name="websiteType" value="Fitness Coach Website"/><input type="hidden" name="budget" value="Example coaching enquiry"/><input type="hidden" name="business" value="FitForm Coaching concept"/><div className="grid gap-4 md:grid-cols-3"><Field label="Name" name="name"/><Field label="Email" name="email" type="email"/><Field label="Phone / WhatsApp" name="phone" type="tel"/></div><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Main goal"><select name="mainGoal" value={mainGoal} onChange={e=>setMainGoal(e.target.value)} className="mt-2 min-h-[52px] w-full rounded-2xl border border-white/10 bg-[#151b24] p-4 text-white"><option value="">Select goal</option>{fitFormConcept.goals.map(g=><option key={g.title}>{g.title}</option>)}</select></Field><Field label="Training experience" name="experience"/></div><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Preferred coaching type" name="coachingType"/><Field label="Current training frequency" name="frequency"/></div><Field label="Biggest struggle" name="struggle"/><label className="mt-4 block text-sm font-bold text-slate-200">Message<textarea name="message" rows="4" className="mt-2 min-h-28 w-full rounded-2xl border border-white/10 bg-white/10 p-4 text-white outline-none" defaultValue="Fitness Coach Website — example coaching enquiry."/></label><button className="fitform-btn mt-5 rounded-full bg-lime-300 px-7 py-4 font-black text-[#071008]">Send Coaching Enquiry</button><p className="mt-4 text-sm text-slate-400">This is a concept enquiry form showing how coaching enquiries could be qualified.</p></form></div></Section>}
