import { useEffect, useState } from 'react';
import { CalendarCheck, ChevronDown, ExternalLink, Heart, MapPin, Phone, Sparkles, Star, X } from 'lucide-react';
import { glowHausConcept } from '../data/siteContent';
import Reveal from '../components/Reveal';

const categories = Object.keys(glowHausConcept.categories);
const beforeImages = [
  'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=900&q=80',
];
const afterImages = [
  'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=900&q=80',
  'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=900&q=80',
];

export default function GlowHausConcept({ onBack }) {
  const [category, setCategory] = useState('Lashes');
  const [treatment, setTreatment] = useState('');
  const [activeImage, setActiveImage] = useState(null);
  const [openFaq, setOpenFaq] = useState(0);
  const [sent, setSent] = useState(false);
  const [cursor, setCursor] = useState({ x: -200, y: -200 });

  useEffect(() => { window.scrollTo({ top: 0, left: 0, behavior: 'auto' }); }, []);
  useEffect(() => {
    const move = (event) => setCursor({ x: event.clientX, y: event.clientY });
    window.addEventListener('pointermove', move);
    return () => window.removeEventListener('pointermove', move);
  }, []);

  const scrollTo = (id) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
  const book = (name = '') => { setTreatment(name); scrollTo('glowhaus-booking'); };
  const clientEnquiry = () => {
    window.sessionStorage.setItem('prefillWebsiteType', 'Beauty Salon Website');
    window.sessionStorage.setItem('prefillProjectMessage', 'I want a premium beauty salon website in the GlowHaus style.');
    onBack?.();
    window.setTimeout(() => scrollTo('contact'), 120);
  };

  return <div className="glowhaus-page min-h-screen overflow-x-hidden bg-[#fbf3ea] text-[#3c2924]">
    <div className="pointer-events-none fixed z-50 hidden h-56 w-56 -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#e7b8b2]/25 blur-3xl lg:block" style={{ left: cursor.x, top: cursor.y }} />
    <header className="sticky top-0 z-40 border-b border-[#7b5148]/10 bg-[#fff9f4]/85 px-4 py-3 backdrop-blur-xl sm:px-5"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3"><button onClick={onBack} className="rounded-full border border-[#7b5148]/15 px-4 py-2 text-sm text-[#7b5148] hover:bg-[#7b5148]/5">← Back to portfolio</button><button onClick={clientEnquiry} className="glow-shimmer rounded-full bg-[#7b5148] px-5 py-2.5 text-sm font-bold text-[#fff9f4]">Use this style for my beauty business</button></div></header>

    <section className="relative isolate overflow-hidden px-4 py-16 sm:px-5 lg:min-h-[92vh] lg:py-24">
      <div className="absolute inset-0 -z-20 bg-[radial-gradient(circle_at_15%_20%,rgba(232,184,178,.55),transparent_24rem),radial-gradient(circle_at_82%_12%,rgba(222,191,138,.35),transparent_22rem),linear-gradient(135deg,#fffaf5,#f7e4df_55%,#efe0d2)]" />
      <div className="noise-overlay" />
      <div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1fr_.86fr]"><Reveal><p className="mb-5 inline-flex rounded-full border border-[#b8867d]/25 bg-white/45 px-4 py-2 text-sm uppercase tracking-[0.28em] text-[#8a5a51]">GlowHaus Beauty Studio · Cape Town</p><h1 className="font-serif text-6xl font-semibold leading-[.92] tracking-[-.06em] text-[#3c2924] sm:text-7xl lg:text-8xl">Beauty, softly elevated.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#684c45] sm:text-xl">A boutique Cape Town beauty studio for refined treatments, glowing skin, polished details and feel-good confidence.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={()=>book()} className="glow-shimmer rounded-full bg-[#7b5148] px-7 py-4 font-bold text-white shadow-2xl shadow-[#b8867d]/25">Book a Treatment</button><button onClick={()=>scrollTo('glowhaus-services')} className="rounded-full border border-[#7b5148]/20 bg-white/45 px-7 py-4 font-bold text-[#5a3933] backdrop-blur hover:bg-white/70">Explore Services</button></div><div className="mt-8 grid max-w-3xl grid-cols-2 gap-3 sm:grid-cols-4">{glowHausConcept.trustBadges.map(b=><span key={b} className="rounded-2xl border border-white/55 bg-white/45 p-3 text-sm text-[#654841] backdrop-blur">{b}</span>)}</div></Reveal>
      <Reveal delay={0.08} className="relative"><img src={glowHausConcept.images.hero.src} alt={glowHausConcept.images.hero.alt} className="h-[36rem] w-full rounded-[3rem] object-cover shadow-2xl shadow-[#8a5a51]/20"/><div className="absolute -bottom-6 left-6 right-6 rounded-[2rem] border border-white/60 bg-white/70 p-5 shadow-2xl backdrop-blur-xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#a87468]">Request appointment</p><div className="mt-3 grid gap-3 sm:grid-cols-3"><Mini label="Treatment type"/><Mini label="Preferred date" type="date"/><Mini label="Preferred time" type="time"/></div><button onClick={()=>book('GlowHaus appointment request')} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-full bg-[#3c2924] px-5 py-3 font-bold text-white"><CalendarCheck size={18}/> Request Appointment</button>{sent && <p className="mt-3 text-sm text-[#7b5148]">Request noted — complete the form below.</p>}</div></Reveal></div>
    </section>

    <main>
      <Section id="glowhaus-story"><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><Reveal><Intro eyebrow="Welcome" title="A calm, curated studio for polished natural confidence." text="GlowHaus was created for clients who want beauty treatments that feel considered, calm and beautifully finished. From soft glam makeup to brows, lashes, nails and skin-focused treatments, every appointment is shaped around natural confidence and polished detail."/><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{glowHausConcept.highlights.map(h=><span key={h} className="rounded-2xl border border-[#b8867d]/15 bg-white/60 p-4 text-sm text-[#654841]">{h}</span>)}</div></Reveal><Reveal><img src={glowHausConcept.images.story.src} alt={glowHausConcept.images.story.alt} loading="lazy" decoding="async" className="h-[34rem] w-full rounded-[2.5rem] object-cover shadow-xl shadow-[#b8867d]/15"/></Reveal></div></Section>

      <Section id="glowhaus-services"><Intro eyebrow="Treatment menu" title="Services that feel easy to choose and beautiful to book." text="Category tabs keep the service menu quick, polished and mobile-friendly."/><div className="mb-8 flex gap-2 overflow-x-auto pb-2">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`min-h-[44px] shrink-0 rounded-full px-5 font-bold transition ${category===c?'bg-[#7b5148] text-white':'border border-[#7b5148]/15 bg-white/50 text-[#684c45]'}`}>{c}</button>)}</div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{glowHausConcept.categories[category].map(([name, desc, duration, price, best])=><article key={name} className="group rounded-[2rem] border border-[#b8867d]/15 bg-white/60 p-5 shadow-lg shadow-[#b8867d]/10 transition duration-500 hover:-translate-y-1 hover:bg-white"><div className="flex items-start justify-between gap-3"><h3 className="text-xl font-semibold">{name}</h3><strong className="text-[#a87468]">{price}</strong></div><p className="mt-3 leading-7 text-[#6d514a]">{desc}</p><div className="mt-4 grid grid-rows-[0fr] transition-all duration-500 group-hover:grid-rows-[1fr]"><div className="overflow-hidden"><p className="rounded-2xl bg-[#f3dfda] p-3 text-sm"><b>{duration}</b> · Best for {best}</p></div></div><button onClick={()=>book(name)} className="mt-4 rounded-full border border-[#7b5148]/20 px-4 py-2 font-bold text-[#7b5148]">Book This</button></article>)}</div></Section>

      <Section className="bg-[#3c2924] text-[#fff9f4]"><Intro light eyebrow="Signature services" title="Campaign-style highlights for premium treatments." text="Visual service cards help visitors imagine the result before they book."/><div className="grid gap-6 lg:grid-cols-3">{glowHausConcept.signatures.map(s=><article key={s.title} className="overflow-hidden rounded-[2.5rem] bg-white/10"><img src={s.image.src} alt={s.image.alt} loading="lazy" decoding="async" className="h-72 w-full object-cover transition duration-700 hover:scale-105"/><div className="p-6"><h3 className="text-2xl font-semibold">{s.title}</h3><p className="mt-3 text-[#eadbd5]">{s.for}</p><p className="mt-3 text-[#eadbd5]"><b>Included:</b> {s.includes}</p><p className="mt-4 font-bold text-[#e8c9a0]">{s.duration} · {s.price}</p><button onClick={()=>book(s.title)} className="mt-5 rounded-full bg-[#f6ddd6] px-5 py-3 font-bold text-[#3c2924]">Book This</button></div></article>)}</div></Section>

      <Section><Intro eyebrow="Transformations" title="Before / after moments with a soft reveal." text="Example transformation cards use a lightweight comparison slider and illustrative imagery."/><div className="grid gap-6 lg:grid-cols-3">{glowHausConcept.transformations.map(([title,text],i)=><Transform key={title} title={title} text={text} before={beforeImages[i]} after={afterImages[i]} />)}</div><p className="mt-5 text-sm text-[#7b5148]">Results vary by client. Example images are shown for example layout.</p></Section>

      <Section className="bg-[#fff9f4]"><Intro eyebrow="Gallery" title="An editorial beauty grid made for Instagram-friendly browsing." text="Click any photo to open a soft lightbox. Images are illustrative and chosen to support the visual direction."/><div className="columns-1 gap-4 sm:columns-2 lg:columns-3">{glowHausConcept.gallery.map((image,i)=><button key={image.src} onClick={()=>setActiveImage(image)} className="group mb-4 block w-full overflow-hidden rounded-[2rem] bg-white text-left shadow-lg"><img src={image.src} alt={image.alt} loading="lazy" decoding="async" className={`${i%3===0?'h-80':'h-64'} w-full object-cover transition duration-700 group-hover:scale-105 group-hover:blur-[1px]`}/><span className="block px-4 py-3 text-xs text-[#7b5148]">Illustrative image</span></button>)}</div></Section>

      <Section><Intro eyebrow="Specialists" title="A trusted team clients can book with confidence." text="Specialist profiles make a salon feel personal, skilled and easy to choose."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{glowHausConcept.team.map(([name,role,spec,bio,img])=><article key={name} className="rounded-[2rem] border border-[#b8867d]/15 bg-white/60 p-4"><img src={img} alt={`${name}, ${role}`} loading="lazy" decoding="async" className="h-64 w-full rounded-[1.5rem] object-cover"/><h3 className="mt-4 text-xl font-semibold">{name}</h3><p className="text-[#a87468]">{role}</p><p className="mt-3 text-sm leading-6 text-[#6d514a]">{bio}</p><p className="mt-3 text-sm"><b>Specialties:</b> {spec}</p><button onClick={()=>book(`Book with ${name}`)} className="mt-4 rounded-full border border-[#7b5148]/20 px-4 py-2 font-bold text-[#7b5148]">Book with this specialist</button></article>)}</div></Section>

      <Section className="bg-[#f3dfda]"><div className="grid gap-8 lg:grid-cols-[1fr_.75fr]"><div><Intro eyebrow="Care philosophy" title="Trust-building details for beauty clients." text="A premium beauty website should make hygiene, product quality and aftercare feel clear before a client arrives."/><div className="grid gap-3 sm:grid-cols-2">{glowHausConcept.philosophy.map(p=><p key={p} className="rounded-2xl bg-white/60 p-4"><Sparkles className="mb-2 text-[#a87468]"/> {p}</p>)}</div></div><aside className="rounded-[2rem] bg-[#3c2924] p-6 text-[#fff9f4]"><h3 className="text-2xl font-semibold">Aftercare matters</h3>{['Avoid steam after lash treatments','Follow product guidance','Keep nails moisturised','Use SPF after facials','Book maintenance appointments'].map(x=><p key={x} className="mt-4 border-t border-white/10 pt-4">{x}</p>)}</aside></div></Section>

      <BookingSection treatment={treatment} setTreatment={setTreatment} setSent={setSent}/>
      <Section><div className="grid gap-8 lg:grid-cols-2"><div><Intro eyebrow="Hours & studio" title="Practical details with polished booking paths." text="GlowHaus is presented as a by-appointment Cape Town concept studio."/><div>{glowHausConcept.hours.map(([d,h])=><p key={d} className="flex justify-between rounded-2xl border border-[#b8867d]/15 bg-white/60 p-4"><span>{d}</span><b>{h}</b></p>)}</div></div><div className="grid place-items-center rounded-[2.5rem] bg-[radial-gradient(circle_at_30%_20%,rgba(232,184,178,.55),transparent_16rem),linear-gradient(135deg,#fff9f4,#e9d5cb)] p-6 text-center"><MapPin className="mb-4 text-[#a87468]" size={44}/><h3 className="text-3xl font-semibold">Cape Town, South Africa</h3><p className="mt-3">Illustrative contact area shown for concept layout only.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><button onClick={()=>book()} className="rounded-full bg-[#7b5148] px-5 py-3 font-bold text-white">Book Appointment</button><button onClick={clientEnquiry} className="rounded-full border border-[#7b5148]/20 px-5 py-3 font-bold text-[#7b5148]">Use This Style</button><a href="https://www.google.com/maps/search/Cape+Town+beauty+studio" target="_blank" rel="noreferrer" className="rounded-full border border-[#7b5148]/20 px-5 py-3 font-bold text-[#7b5148]">Get Directions <ExternalLink className="inline" size={15}/></a></div></div></div></Section>

      <Section className="bg-[#fff9f4]"><Intro eyebrow="Reviews" title="Soft proof for confident appointments." text="Testimonials show the calm, clean and professional experience clients expect."/><div className="grid gap-5 lg:grid-cols-3">{glowHausConcept.reviews.map(([n,t,r])=><article key={n} className="rounded-[2rem] bg-white p-6 shadow-xl shadow-[#b8867d]/10"><div className="flex gap-1 text-[#b8867d]">{Array.from({length:5}).map((_,i)=><Star key={i} size={18} fill="currentColor" />)}</div><p className="mt-5 leading-8 text-[#654841]">“{r}”</p><p className="mt-5 font-semibold">{n}</p><p className="text-sm text-[#a87468]">{t}</p></article>)}</div></Section>
      <Section><Intro eyebrow="FAQ" title="Beauty-specific answers before clients book." text="Accordion FAQs keep long content tidy on mobile."/>{glowHausConcept.faqs.map((f,i)=><div key={f.question} className="border-t border-[#7b5148]/15 py-2"><button onClick={()=>setOpenFaq(openFaq===i?-1:i)} className="flex w-full items-center justify-between gap-4 py-4 text-left font-semibold"><span>{f.question}</span><ChevronDown className={`shrink-0 transition ${openFaq===i?'rotate-180':''}`}/></button>{openFaq===i && <p className="pb-4 leading-7 text-[#6d514a]">{f.answer}</p>}</div>)}</Section>
      <Section><div className="rounded-[2.5rem] bg-[#3c2924] p-8 text-center text-[#fff9f4] sm:p-12"><Heart className="mx-auto text-[#f6ddd6]"/><h2 className="mt-4 font-serif text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Ready for your glow appointment?</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-[#eadbd5]">Choose your treatment, send your preferred time and we’ll confirm the perfect appointment for you.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><button onClick={()=>book()} className="glow-shimmer rounded-full bg-[#f6ddd6] px-7 py-4 font-bold text-[#3c2924]">Book a Treatment</button><button onClick={()=>scrollTo('glowhaus-services')} className="rounded-full border border-white/15 px-7 py-4 font-bold">View Services</button><button onClick={clientEnquiry} className="rounded-full border border-white/15 px-7 py-4 font-bold">Use This Style</button></div><button onClick={clientEnquiry} className="mt-5 rounded-full bg-white px-7 py-4 font-bold text-[#3c2924]">Use this style for my beauty business</button><p className="mx-auto mt-6 max-w-3xl rounded-2xl border border-white/10 bg-white/5 p-4 text-sm leading-6 text-[#eadbd5]">This concept website shows how a business in this industry could be presented online. Images, prices, services, reviews and business details are illustrative.</p></div></Section>
    </main>
    <button onClick={()=>book()} className="fixed bottom-4 left-4 right-4 z-40 rounded-full bg-[#7b5148] px-5 py-4 font-bold text-white shadow-2xl sm:hidden">Book a Glow Session</button>
    {activeImage && <Lightbox image={activeImage} onClose={()=>setActiveImage(null)} />}
  </div>;
}
function Section({ children, id, className='' }) { return <section id={id} className={`px-4 py-20 sm:px-5 ${className}`}><div className="mx-auto max-w-7xl">{children}</div></section>; }
function Intro({ eyebrow, title, text, light=false }) { return <div className="mb-10 max-w-3xl"><p className={`text-sm uppercase tracking-[.25em] ${light?'text-[#e8c9a0]':'text-[#a87468]'}`}>{eyebrow}</p><h2 className={`mt-3 font-serif text-4xl font-semibold tracking-[-.04em] sm:text-5xl ${light?'text-white':'text-[#3c2924]'}`}>{title}</h2><p className={`mt-4 text-lg leading-8 ${light?'text-[#eadbd5]':'text-[#6d514a]'}`}>{text}</p></div>; }
function Mini({ label, type='text' }) { return <label className="text-xs font-semibold text-[#7b5148]">{label}<input type={type} className="mt-1 w-full rounded-2xl border border-[#7b5148]/10 bg-white/70 p-3 outline-none" /></label>; }
function Field({ label, name, type='text', value, onChange, required=false }) { return <label className="block text-sm font-medium text-[#684c45]">{label}<input name={name} type={type} value={value} onChange={onChange} required={required} className="mt-2 min-h-[52px] w-full rounded-2xl border border-[#b8867d]/20 bg-white/70 p-4 text-[#3c2924] outline-none focus:border-[#a87468]" /></label>; }
function BookingSection({ treatment, setTreatment, setSent }) { return <Section id="glowhaus-booking" className="bg-[#3c2924] text-[#fff9f4]"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><Intro light eyebrow="Appointments" title="Request a glow session in seconds." text="This is a concept enquiry form showing how appointments could be requested."/><form name="project-enquiry" method="POST" action="/" data-netlify="true" className="rounded-[2rem] border border-white/10 bg-white/10 p-5 sm:p-6"><input type="hidden" name="form-name" value="project-enquiry"/><input type="hidden" name="websiteType" value="Beauty Salon Website"/><input type="hidden" name="budget" value="Example appointment enquiry"/><input type="hidden" name="business" value="GlowHaus Beauty Studio example appointment"/><div className="grid gap-4 md:grid-cols-3"><Field label="Name" name="name" required/><Field label="Email" name="email" type="email" required/><Field label="Phone / WhatsApp" name="phone" type="tel"/></div><div className="mt-4 grid gap-4 md:grid-cols-3"><label className="block text-sm font-medium text-[#eadbd5]">Treatment type<select name="treatmentType" value={treatment} onChange={e=>setTreatment(e.target.value)} className="mt-2 min-h-[52px] w-full rounded-2xl border border-white/10 bg-[#4d332d] p-4 text-white"><option value="">Select treatment</option>{categories.map(c=><optgroup key={c} label={c}>{glowHausConcept.categories[c].map(([n])=><option key={n}>{n}</option>)}</optgroup>)}</select></label><Field label="Preferred date" name="date" type="date"/><Field label="Preferred time" name="time" type="time"/></div><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="block text-sm font-medium text-[#eadbd5]">New or returning client<select name="clientType" className="mt-2 min-h-[52px] w-full rounded-2xl border border-white/10 bg-[#4d332d] p-4 text-white"><option>New client</option><option>Returning client</option></select></label><Field label="Occasion (optional)" name="occasion" /></div><label className="mt-4 block text-sm font-medium text-[#eadbd5]">Message / treatment notes<textarea name="message" rows="4" className="mt-2 min-h-28 w-full resize-y rounded-2xl border border-white/10 bg-[#4d332d] p-4 text-white outline-none" defaultValue="Beauty Salon Website — example appointment enquiry." /></label><button onClick={()=>setSent(true)} className="glow-shimmer mt-5 rounded-full bg-[#f6ddd6] px-7 py-4 font-bold text-[#3c2924]">Request Appointment</button><p className="mt-4 text-sm text-[#eadbd5]">This is a concept enquiry form showing how appointments could be requested.</p></form></div></Section>; }
function Transform({ title, text, before, after }) { const [v,setV]=useState(50); return <article className="rounded-[2rem] border border-[#b8867d]/15 bg-white/60 p-4"><div className="relative h-72 overflow-hidden rounded-[1.5rem]"><img src={before} alt={`${title} before example`} loading="lazy" decoding="async" className="absolute inset-0 h-full w-full object-cover"/><img src={after} alt={`${title} after example`} loading="lazy" decoding="async" className="absolute inset-0 h-full w-full object-cover" style={{clipPath:`inset(0 0 0 ${v}%)`}}/><span className="absolute left-3 top-3 rounded-full bg-white/80 px-3 py-1 text-xs">Before</span><span className="absolute right-3 top-3 rounded-full bg-white/80 px-3 py-1 text-xs">After</span></div><input aria-label={`${title} before and after slider`} type="range" min="10" max="90" value={v} onChange={e=>setV(e.target.value)} className="mt-4 w-full accent-[#7b5148]"/><h3 className="mt-3 text-xl font-semibold">{title}</h3><p className="mt-2 text-[#6d514a]">{text}</p></article>; }
function Lightbox({ image, onClose }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-[#3c2924]/85 p-4 backdrop-blur" role="dialog" aria-modal="true"><button onClick={onClose} className="absolute right-5 top-5 grid h-11 w-11 place-items-center rounded-full bg-white/15 text-white"><X /></button><figure className="max-w-5xl"><img src={image.src} alt={image.alt} className="max-h-[82vh] rounded-[2rem] object-contain shadow-2xl"/><figcaption className="mt-3 text-center text-sm text-[#fff9f4]">{image.alt} · Illustrative image</figcaption></figure></div>; }
