import { useEffect, useState } from 'react';
import { Building2, CheckCircle2, ChevronDown, ClipboardCheck, Hammer, HardHat, Home, Layers3, MapPin, Ruler, ShieldCheck, Shovel, Star, Wrench, X } from 'lucide-react';
import { primeBuildConcept } from '../data/siteContent';
import Reveal from '../components/Reveal';
import BackToConceptsButton from '../components/BackToConceptsButton';

const iconMap = { Home, Hammer, Building2, Layers3, ClipboardCheck, HardHat, Wrench, ShieldCheck, Shovel, Ruler };

export default function PrimeBuildConcept({ onBack }) {
  const [activeProject, setActiveProject] = useState(null);
  const [openFaq, setOpenFaq] = useState(0);
  const [quoteStarted, setQuoteStarted] = useState(false);

  useEffect(() => window.scrollTo({ top: 0, left: 0, behavior: 'auto' }), []);

  const scrollTo = (id) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
  const clientEnquiry = (message = 'I want a construction company website like this PrimeBuild concept.') => {
    window.sessionStorage.setItem('prefillWebsiteType', 'Construction Company Website');
    window.sessionStorage.setItem('prefillProjectMessage', message);
    window.dispatchEvent(new CustomEvent('select-website-type', { detail: 'Construction Company Website' }));
    window.dispatchEvent(new CustomEvent('prefill-project-message', { detail: message }));
    onBack?.();
    window.setTimeout(() => document.getElementById('contact')?.scrollIntoView({ behavior: 'smooth' }), 80);
  };
  const startQuote = () => { setQuoteStarted(true); scrollTo('primebuild-quote'); };

  return (
    <div className="min-h-screen overflow-x-hidden bg-[#080d12] text-[#f7f2e8]">
      <BackToConceptsButton onBack={onBack} />
      <header className="sticky top-0 z-40 border-b border-white/10 bg-[#080d12]/90 px-4 py-3 backdrop-blur-xl sm:px-5">
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-3">
          <button onClick={onBack} className="rounded-full border border-white/15 px-4 py-2 text-sm text-[#f2c66d] hover:bg-white/5">← Back to Concepts</button>
          <button onClick={() => clientEnquiry()} className="rounded-full bg-[#d69b2d] px-5 py-2.5 text-sm font-bold text-[#081018]">Use this style for my construction company</button>
        </div>
      </header>

      <section className="relative isolate flex min-h-[92vh] items-center overflow-hidden px-4 py-16 sm:px-5">
        <img src={primeBuildConcept.images.hero.src} alt={primeBuildConcept.images.hero.alt} className="absolute inset-0 -z-20 h-full w-full object-cover" />
        <div className="absolute inset-0 -z-10 bg-[linear-gradient(115deg,rgba(5,10,16,.96),rgba(8,13,18,.82)_46%,rgba(12,34,50,.58)),linear-gradient(180deg,transparent,rgba(8,13,18,.95))]" />
        <div className="absolute inset-0 -z-10 opacity-25 [background-image:linear-gradient(rgba(255,255,255,.09)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.08)_1px,transparent_1px)] [background-size:56px_56px]" />
        <div className="mx-auto grid w-full max-w-7xl items-end gap-8 lg:grid-cols-[1.05fr_.72fr]">
          <Reveal>
            <p className="mb-5 inline-flex rounded-full border border-[#d69b2d]/35 bg-[#d69b2d]/10 px-4 py-2 text-sm uppercase tracking-[0.28em] text-[#f2c66d]">PrimeBuild Construction · Cape Town</p>
            <h1 className="max-w-4xl text-4xl font-semibold leading-[0.98] tracking-[-0.055em] text-white sm:text-6xl lg:text-8xl">Built with precision. Delivered with pride.</h1>
            <p className="mt-6 max-w-2xl text-lg leading-8 text-[#d8e2e8] sm:text-xl">Professional construction, renovation and project delivery services for homes, businesses and developments across Cape Town.</p>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={startQuote} className="premium-button rounded-full bg-[#d69b2d] px-7 py-4 font-bold text-[#081018]">Request a Quote</button><button onClick={() => scrollTo('primebuild-projects')} className="rounded-full border border-white/20 bg-white/10 px-7 py-4 font-bold text-white backdrop-blur hover:bg-white/15">View Projects</button></div>
            <div className="mt-8 grid max-w-3xl grid-cols-2 gap-3 sm:grid-cols-4">{primeBuildConcept.trustBadges.map((badge) => <span key={badge} className="rounded-2xl border border-white/10 bg-black/25 p-3 text-sm text-[#f8ead1] backdrop-blur">{badge}</span>)}</div>
          </Reveal>
          <Reveal delay={0.08} className="rounded-[2rem] border border-[#d69b2d]/25 bg-[#f7f2e8]/95 p-5 text-[#081018] shadow-2xl shadow-black/40">
            <p className="text-sm font-bold uppercase tracking-[0.2em] text-[#8a641e]">Start a quote</p>
            <div className="mt-5 grid gap-3"><QuoteMiniField label="Project type" placeholder="Renovation, new build, fit-out" /><QuoteMiniField label="Location" placeholder="e.g. Durbanville" /><QuoteMiniField label="Estimated timeline" placeholder="e.g. 3–6 months" /></div>
            <button onClick={startQuote} className="mt-5 inline-flex min-h-[52px] w-full items-center justify-center gap-2 rounded-full bg-[#081018] px-5 font-bold text-white"><ClipboardCheck size={18} /> Start Quote</button>
            {quoteStarted && <p className="mt-4 rounded-2xl bg-[#ead4a5] p-3 text-sm text-[#443012]">Quote flow started — complete the enquiry section below.</p>}
          </Reveal>
        </div>
      </section>

      <main>
        <Notice />
        <section className="px-4 py-20 sm:px-5"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><Reveal><Intro eyebrow="Company" title="Construction teams, clear management, quality finishes." text={primeBuildConcept.about} /><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3">{primeBuildConcept.stats.map((item)=><span key={item} className="rounded-2xl border border-white/10 bg-white/[0.06] p-4 text-sm text-[#e8edf0]">{item}</span>)}</div></Reveal><Reveal delay={0.08}><img src={primeBuildConcept.images.about.src} alt={primeBuildConcept.images.about.alt} loading="lazy" decoding="async" className="h-[34rem] w-full rounded-[2.5rem] object-cover shadow-2xl shadow-black/30" /></Reveal></div></section>

        <section className="bg-[#f5efe2] px-4 py-20 text-[#081018] sm:px-5"><div className="mx-auto max-w-7xl"><Intro dark eyebrow="Services" title="From groundwork to handover." text="Detailed service cards help builders and contractors sell their capability without feeling generic."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{primeBuildConcept.services.map((service)=>{const Icon=iconMap[service.icon]||Hammer;return <article key={service.title} className="rounded-[1.75rem] bg-white p-5 shadow-xl shadow-[#081018]/10"><Icon className="text-[#b57917]"/><h3 className="mt-4 text-xl font-semibold">{service.title}</h3><p className="mt-3 text-sm leading-6 text-[#56616c]">{service.description}</p><p className="mt-4 rounded-2xl bg-[#eef3f5] p-3 text-xs font-bold text-[#203443]">Best for: {service.bestFor}</p><button onClick={startQuote} className="mt-4 rounded-full border border-[#b57917]/30 px-4 py-2 text-sm font-bold text-[#8a641e]">Enquire</button></article>})}</div></div></section>

        <section id="primebuild-projects" className="px-4 py-20 sm:px-5"><div className="mx-auto max-w-7xl"><Intro eyebrow="Project portfolio" title="Example case studies with real contractor detail." text="Each project card includes scope, timeline and outcome details a construction client expects to see."/><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{primeBuildConcept.projects.map((project)=><article key={project.name} className="overflow-hidden rounded-[2rem] border border-white/10 bg-white/[0.055]"><img src={project.image.src} alt={project.image.alt} loading="lazy" decoding="async" className="h-64 w-full object-cover transition duration-700 hover:scale-105"/><div className="p-6"><p className="text-sm font-bold text-[#f2c66d]">{project.category}</p><h3 className="mt-2 text-2xl font-semibold text-white">{project.name}</h3><p className="mt-3 text-sm text-[#9fb2bf]">{project.location} · {project.timeline}</p><p className="mt-3 leading-7 text-[#d7e0e5]">{project.description}</p><ul className="mt-4 space-y-2 text-sm text-[#c7d1d8]">{project.scope.slice(0,3).map(s=><li key={s} className="flex gap-2"><CheckCircle2 size={16} className="mt-1 text-[#d69b2d]" />{s}</li>)}</ul><button onClick={()=>setActiveProject(project)} className="mt-5 rounded-full bg-[#d69b2d] px-5 py-3 font-bold text-[#081018]">View Project</button></div></article>)}</div></div></section>

        <section className="bg-[#f5efe2] px-4 py-20 text-[#081018] sm:px-5"><div className="mx-auto max-w-7xl"><Intro dark eyebrow="Renovation outcomes" title="From tired spaces to finished homes." text="Side-by-side visuals show transformation storytelling with a clean, easy-to-scan layout."/><div className="grid gap-5 lg:grid-cols-3">{primeBuildConcept.beforeAfter.map((item)=><article key={item.title} className="rounded-[2rem] bg-white p-4 shadow-xl shadow-[#081018]/10"><div className="grid gap-3 sm:grid-cols-2"><figure className="overflow-hidden rounded-2xl"><img src={item.before.src} alt={item.before.alt} loading="lazy" decoding="async" className="h-56 w-full object-cover transition duration-500 hover:scale-105"/><figcaption className="bg-[#18232d] px-3 py-2 text-xs font-bold text-white">Before</figcaption></figure><figure className="overflow-hidden rounded-2xl"><img src={item.after.src} alt={item.after.alt} loading="lazy" decoding="async" className="h-56 w-full object-cover transition duration-500 hover:scale-105"/><figcaption className="bg-[#d69b2d] px-3 py-2 text-xs font-bold text-[#081018]">After</figcaption></figure></div><h3 className="mt-5 text-xl font-semibold">{item.title}</h3><p className="mt-2 leading-7 text-[#56616c]">{item.text}</p></article>)}</div></div></section>

        <section className="px-4 py-20 sm:px-5"><div className="mx-auto max-w-7xl"><Intro eyebrow="Safety & compliance" title="Built on planning, quality control and clean handover." text="Trust sections position construction firms as organised, safety-conscious and capable of serious work."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{primeBuildConcept.safety.map((item)=><article key={item.title} className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-6"><ShieldCheck className="text-[#d69b2d]"/><h3 className="mt-5 text-xl font-semibold text-white">{item.title}</h3><p className="mt-3 leading-7 text-[#cbd7de]">{item.text}</p></article>)}</div><div className="mt-8 flex flex-wrap gap-3">{primeBuildConcept.complianceBadges.map((badge)=><span key={badge} className="rounded-full border border-[#d69b2d]/30 bg-[#d69b2d]/10 px-4 py-2 text-sm text-[#f2c66d]">{badge}</span>)}</div><p className="mt-5 text-sm text-[#9fb2bf]">Example certification and compliance details are shown for example layout.</p></div></section>

        <ProcessSection />
        <AreasSection onAsk={startQuote} />
        <QuoteSection />
        <Testimonials />
        <FaqSection openFaq={openFaq} setOpenFaq={setOpenFaq} />
        <section className="px-4 pb-24 sm:px-5"><div className="mx-auto max-w-5xl rounded-[2.5rem] border border-[#d69b2d]/30 bg-[linear-gradient(135deg,rgba(214,155,45,.27),rgba(255,255,255,.05)),#0b1219] p-8 text-center shadow-2xl sm:p-12"><p className="text-sm uppercase tracking-[0.25em] text-[#f2c66d]">Final CTA</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.04em] text-white sm:text-6xl">Planning a build or renovation?</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-[#d7e0e5]">Tell us what you want to create and we’ll guide you through the next step.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><button onClick={startQuote} className="rounded-full bg-[#d69b2d] px-7 py-4 font-bold text-[#081018]">Request a Quote</button><button onClick={()=>scrollTo('primebuild-projects')} className="rounded-full border border-white/15 px-7 py-4 font-bold text-white">View Projects</button><button onClick={()=>clientEnquiry()} className="rounded-full border border-[#d69b2d]/35 px-7 py-4 font-bold text-[#f2c66d]">Discuss This Website Style</button></div><button onClick={()=>clientEnquiry()} className="mt-5 rounded-full bg-[#f5efe2] px-7 py-4 font-bold text-[#081018]">Use this style for my construction company</button><p className="mx-auto mt-6 max-w-3xl rounded-2xl border border-white/10 bg-white/5 p-4 text-sm leading-6 text-[#cbd7de]">This concept website shows how a business in this industry could be presented online. Images, prices, services, reviews and business details are illustrative.</p></div></section>
      </main>
      {activeProject && <ProjectModal project={activeProject} onClose={()=>setActiveProject(null)} onQuote={()=>{setActiveProject(null); startQuote();}} />}
    </div>
  );
}

function QuoteMiniField({ label, placeholder }) { return <label className="text-sm font-semibold text-[#25313a]">{label}<input placeholder={placeholder} className="mt-2 min-h-[52px] w-full rounded-2xl border border-[#d7c8ab] bg-white px-4 text-[#081018] outline-none focus:border-[#8a641e]" /></label>; }
function Intro({ eyebrow, title, text, dark=false }) { return <div className="mb-10 max-w-3xl"><p className={`text-sm uppercase tracking-[0.25em] ${dark ? 'text-[#8a641e]' : 'text-[#f2c66d]'}`}>{eyebrow}</p><h2 className={`mt-3 text-4xl font-semibold tracking-[-0.04em] sm:text-5xl ${dark ? 'text-[#081018]' : 'text-white'}`}>{title}</h2><p className={`mt-4 text-lg leading-8 ${dark ? 'text-[#56616c]' : 'text-[#cbd7de]'}`}>{text}</p></div>; }
function Notice(){return <section className="px-4 pt-10 sm:px-5"><div className="mx-auto max-w-7xl rounded-3xl border border-[#d69b2d]/25 bg-[#d69b2d]/10 p-5 text-sm leading-6 text-[#f4dca4]">This concept website shows how a business in this industry could be presented online. Images, prices, services, reviews and business details are illustrative.</div></section>}
function ProcessSection(){return <section className="bg-[#101a24] px-4 py-20 sm:px-5"><div className="mx-auto max-w-7xl"><Intro eyebrow="Process" title="A simple six-step build journey." text="The process turns a complex construction project into clear, reassuring milestones."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{primeBuildConcept.process.map((step,index)=><article key={step.title} className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-6"><span className="grid h-12 w-12 place-items-center rounded-full bg-[#d69b2d] font-bold text-[#081018]">{index+1}</span><h3 className="mt-5 text-xl font-semibold text-white">{step.title}</h3><p className="mt-3 leading-7 text-[#cbd7de]">{step.text}</p></article>)}</div></div></section>}
function AreasSection({ onAsk }){return <section className="px-4 py-20 sm:px-5"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.85fr_1.15fr]"><div><Intro eyebrow="Service areas" title="Construction services across Cape Town." text="A local service-area block improves relevance for builders, renovators and civil contractors."/><div className="grid grid-cols-2 gap-3">{primeBuildConcept.serviceAreas.map(area=><span key={area} className="rounded-2xl border border-white/10 bg-white/[0.055] p-4 text-sm text-[#e2eaef]">{area}</span>)}</div><button onClick={onAsk} className="mt-6 rounded-full bg-[#d69b2d] px-6 py-4 font-bold text-[#081018]">Ask if we work in your area</button></div><div className="rounded-[2rem] border border-[#d69b2d]/25 bg-[radial-gradient(circle_at_30%_20%,rgba(214,155,45,.22),transparent_16rem),linear-gradient(135deg,#172838,#081018)] p-6"><div className="relative grid min-h-96 place-items-center overflow-hidden rounded-[1.5rem] border border-white/10 bg-white/5 text-center"><div className="absolute inset-0 opacity-25 [background-image:linear-gradient(rgba(255,255,255,.12)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.12)_1px,transparent_1px)] [background-size:42px_42px]"/><div className="relative"><MapPin className="mx-auto mb-4 text-[#d69b2d]" size={44}/><h3 className="text-2xl font-semibold text-white">Cape Town coverage map</h3><p className="mt-3 text-[#cbd7de]">Styled map area for quick visitor orientation.</p></div></div></div></div></section>}
function QuoteSection(){return <section id="primebuild-quote" className="bg-[#f5efe2] px-4 py-20 text-[#081018] sm:px-5"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.8fr_1.2fr]"><Intro dark eyebrow="Quote request" title="Tell PrimeBuild what you want to build." text="This concept enquiry form shows how detailed quote requests could be collected for construction leads."/><form name="project-enquiry" method="POST" action="/" data-netlify="true" className="rounded-[2rem] bg-white p-5 shadow-2xl shadow-[#081018]/10 sm:p-6"><input type="hidden" name="form-name" value="project-enquiry"/><input type="hidden" name="websiteType" value="Construction Company Website"/><input type="hidden" name="budget" value="Construction example quote enquiry"/><div className="grid gap-4 md:grid-cols-2"><Field label="Name" name="name" required/><Field label="Company name (optional)" name="business"/><Field label="Email" name="email" type="email" required/><Field label="Phone / WhatsApp" name="phone" type="tel"/><Field label="Project type" name="projectType" placeholder="New build, renovation, fit-out"/><Field label="Project location" name="projectLocation" placeholder="Cape Town suburb"/><Field label="Estimated budget" name="estimatedProjectBudget" placeholder="e.g. R250k - R800k"/><Field label="Ideal start date" name="idealStartDate" type="date"/></div><label className="mt-4 block text-sm font-medium text-[#56616c]">Short project description<textarea name="message" rows="5" className="input-luxury mt-2 min-h-32 resize-y" defaultValue="Construction Company Website — example quote request." /></label><p className="mt-4 rounded-2xl bg-[#eef3f5] p-4 text-sm leading-6 text-[#56616c]">Have plans or photos? Mention this in your message and we’ll request them by email or WhatsApp.</p><button className="premium-button mt-5 rounded-full bg-[#d69b2d] px-7 py-4 font-bold text-[#081018]">Send quote request</button><p className="mt-4 text-sm text-[#6b747d]">This is a concept enquiry form showing how project quote requests could be handled.</p></form></div></section>}
function Field({ label, name, type='text', placeholder='', required=false }) { return <label className="block text-sm font-medium text-[#56616c]">{label}<input name={name} type={type} placeholder={placeholder} required={required} className="input-luxury mt-2 min-h-[52px]" /></label>; }
function Testimonials(){return <section className="px-4 py-20 sm:px-5"><div className="mx-auto max-w-7xl"><Intro eyebrow="Testimonials" title="Reassurance from every type of client." text="Review cards cover renovation, commercial and new-build buyers."/><div className="grid gap-5 lg:grid-cols-3">{primeBuildConcept.testimonials.map((r)=><article key={r.name} className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-6"><div className="flex gap-1 text-[#d69b2d]">{Array.from({length:5}).map((_,i)=><Star key={i} size={18} fill="currentColor"/>)}</div><p className="mt-5 leading-8 text-[#d7e0e5]">“{r.text}”</p><p className="mt-5 font-semibold text-white">{r.name}</p><p className="text-sm text-[#f2c66d]">{r.type}</p></article>)}</div></div></section>}
function FaqSection({ openFaq, setOpenFaq }){return <section className="bg-[#101a24] px-4 py-20 sm:px-5"><div className="mx-auto max-w-4xl"><Intro eyebrow="FAQ" title="Construction questions answered before the first call." text="Accordions keep the page tidy while still covering common quote concerns."/>{primeBuildConcept.faqs.map((item,index)=><div key={item.question} className="border-t border-white/10 py-2"><button onClick={()=>setOpenFaq(openFaq===index ? -1 : index)} className="flex w-full items-center justify-between gap-4 py-4 text-left font-semibold text-[#fff6dd]"><span>{item.question}</span><ChevronDown className={`shrink-0 transition ${openFaq===index ? 'rotate-180' : ''}`} /></button>{openFaq===index && <p className="pb-4 leading-7 text-[#cbd7de]">{item.answer}</p>}</div>)}</div></section>}
function ProjectModal({ project, onClose, onQuote }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="max-h-[92vh] w-full max-w-5xl overflow-auto rounded-[2rem] bg-[#f5efe2] text-[#081018] shadow-2xl"><div className="relative"><img src={project.image.src} alt={project.image.alt} className="h-80 w-full object-cover"/><button onClick={onClose} className="absolute right-4 top-4 grid h-11 w-11 place-items-center rounded-full bg-[#081018]/85 text-white"><X /></button></div><div className="p-6 sm:p-8"><p className="font-bold text-[#8a641e]">{project.category} · {project.location} · {project.timeline}</p><h2 className="mt-2 text-3xl font-semibold">{project.name}</h2><p className="mt-4 leading-8 text-[#56616c]">{project.overview}</p><div className="mt-6 grid gap-5 md:grid-cols-2"><Detail title="Client goal" text={project.goal}/><Detail title="Challenges solved" text={project.challenges}/><Detail title="Final result" text={project.result}/><div><h3 className="font-semibold">Scope of work</h3><ul className="mt-3 space-y-2 text-[#56616c]">{project.scope.map(a=><li key={a} className="flex gap-2"><CheckCircle2 size={17} className="mt-1 text-[#b57917]"/>{a}</li>)}</ul></div></div><button onClick={onQuote} className="mt-7 rounded-full bg-[#081018] px-6 py-4 font-bold text-white">Request Similar Project Quote</button></div></div></div>; }
function Detail({ title, text }) { return <div><h3 className="font-semibold">{title}</h3><p className="mt-3 leading-7 text-[#56616c]">{text}</p></div>; }
