import { useEffect, useState } from 'react';
import { CalendarCheck, ChevronDown, Clock, ExternalLink, MapPin, Phone, Star, X } from 'lucide-react';
import { urbanBiteConcept } from '../data/siteContent';
import Reveal from '../components/Reveal';

const categories = Object.keys(urbanBiteConcept.menu);

export default function UrbanBiteConcept({ onBack }) {
  const [category, setCategory] = useState('Starters');
  const [activeImage, setActiveImage] = useState(null);
  const [openFaq, setOpenFaq] = useState(0);
  const [reserved, setReserved] = useState(false);

  useEffect(() => window.scrollTo({ top: 0, left: 0, behavior: 'auto' }), []);

  const scrollTo = (id) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
  const clientEnquiry = (message = 'I want a restaurant website like this UrbanBite concept.') => {
    window.sessionStorage.setItem('prefillWebsiteType', 'Restaurant Website');
    window.sessionStorage.setItem('prefillProjectMessage', message);
    window.dispatchEvent(new CustomEvent('select-website-type', { detail: 'Restaurant Website' }));
    window.dispatchEvent(new CustomEvent('prefill-project-message', { detail: message }));
    onBack?.();
    window.setTimeout(() => scrollTo('contact'), 80);
  };

  return <div className="min-h-screen overflow-x-hidden bg-[#130f0b] text-[#fff4df]">
    <header className="sticky top-0 z-40 border-b border-white/10 bg-[#130f0b]/90 px-4 py-3 backdrop-blur-xl sm:px-5"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3"><button onClick={onBack} className="rounded-full border border-white/15 px-4 py-2 text-sm text-[#f3d49a] hover:bg-white/5">← Back to portfolio</button><button onClick={() => clientEnquiry()} className="rounded-full bg-[#c87533] px-5 py-2.5 text-sm font-bold text-[#fff7e8]">Use this style for my restaurant</button></div></header>

    <section className="relative isolate grid min-h-[92vh] items-end overflow-hidden px-4 py-16 sm:px-5">
      <img src={urbanBiteConcept.images.hero.src} alt={urbanBiteConcept.images.hero.alt} className="absolute inset-0 -z-20 h-full w-full object-cover" />
      <div className="absolute inset-0 -z-10 bg-gradient-to-br from-[#0b0908]/95 via-[#130f0b]/72 to-[#2a160d]/50" /><div className="absolute inset-x-0 bottom-0 -z-10 h-44 bg-gradient-to-t from-[#130f0b] to-transparent" />
      <div className="mx-auto grid w-full max-w-7xl items-end gap-8 lg:grid-cols-[1.05fr_.7fr]"><Reveal><p className="mb-5 inline-flex rounded-full border border-[#d7a85f]/35 bg-black/35 px-4 py-2 text-sm uppercase tracking-[0.28em] text-[#f3d49a]">UrbanBite Restaurant · Cape Town</p><h1 className="max-w-4xl text-4xl font-semibold leading-[0.98] tracking-[-0.055em] text-white sm:text-6xl lg:text-8xl">Bold flavours. Beautiful nights.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#eadbc4] sm:text-xl">A modern Cape Town bistro serving elevated comfort food, crafted cocktails, and warm city energy.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={() => scrollTo('urbanbite-menu')} className="premium-button rounded-full bg-[#c87533] px-7 py-4 font-bold text-white">View Menu</button><button onClick={() => scrollTo('urbanbite-reservations')} className="rounded-full border border-white/20 bg-white/10 px-7 py-4 font-bold text-white backdrop-blur hover:bg-white/15">Book a Table</button></div><div className="mt-8 grid max-w-3xl grid-cols-2 gap-3 sm:grid-cols-4">{urbanBiteConcept.quickInfo.map((detail) => <span key={detail} className="rounded-2xl border border-white/10 bg-black/25 p-3 text-sm text-[#f8ead1] backdrop-blur">{detail}</span>)}</div></Reveal>
      <Reveal delay={0.08} className="rounded-[2rem] border border-[#d7a85f]/25 bg-[#fff4df]/95 p-5 text-[#1a120d] shadow-2xl shadow-black/30"><p className="text-sm font-bold uppercase tracking-[0.2em] text-[#8a4d24]">Reserve tonight</p><div className="mt-5 grid gap-3 sm:grid-cols-3 lg:grid-cols-1"><Field label="Date" type="date"/><Field label="Time" type="time"/><Field label="Guests" type="number" min="1" placeholder="2"/></div><button onClick={() => { setReserved(true); scrollTo('urbanbite-reservations'); }} className="mt-5 inline-flex min-h-[52px] w-full items-center justify-center gap-2 rounded-full bg-[#1a120d] px-5 font-bold text-white"><CalendarCheck size={18}/> Reserve a Table</button>{reserved && <p className="mt-4 rounded-2xl bg-[#e9d5ad] p-3 text-sm text-[#4b2d18]">Reservation request started — complete the enquiry form below.</p>}</Reveal></div>
    </section>

    <main>
      <section className="px-4 py-20 sm:px-5"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.95fr_1.05fr] lg:items-center"><Reveal><Intro eyebrow="Story" title="City energy, honest food, crafted drinks." text="UrbanBite brings together city energy and honest, flavour-led food. From slow evenings over small plates to celebratory dinners and after-work drinks, every detail is designed to feel relaxed, refined, and memorable."/><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3">{urbanBiteConcept.highlights.map((item)=><span key={item} className="rounded-2xl border border-white/10 bg-white/[0.06] p-4 text-sm text-[#f3e5cb]">{item}</span>)}</div></Reveal><Reveal delay={0.08}><img src={urbanBiteConcept.images.about.src} alt={urbanBiteConcept.images.about.alt} loading="lazy" decoding="async" className="h-[34rem] w-full rounded-[2.5rem] object-cover shadow-2xl shadow-black/30" /></Reveal></div></section>

      <section className="bg-[#fff4df] px-4 py-20 text-[#1a120d] sm:px-5"><div className="mx-auto max-w-7xl"><Intro dark eyebrow="Featured dishes" title="Signature plates with premium casual appeal." text="Dish cards combine photography, clear pricing and appetite-building descriptions for mobile visitors."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{urbanBiteConcept.featuredDishes.map((dish)=><article key={dish.name} className="overflow-hidden rounded-[2rem] bg-white shadow-xl shadow-[#1a120d]/10"><img src={dish.image.src} alt={dish.image.alt} loading="lazy" decoding="async" className="h-60 w-full object-cover transition duration-700 hover:scale-105"/><div className="p-6"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-[#e7f0df] px-3 py-1 text-xs font-bold text-[#516534]">{dish.tag}</span><strong className="text-[#a35c2e]">{dish.price}</strong></div><h3 className="mt-4 text-2xl font-semibold">{dish.name}</h3><p className="mt-3 leading-7 text-[#6a5648]">{dish.description}</p></div></article>)}</div></div></section>

      <section id="urbanbite-menu" className="px-4 py-20 sm:px-5"><div className="mx-auto max-w-7xl"><Intro eyebrow="Interactive menu" title="A real HTML menu — fast to scan, easy to update." text="No PDF required. Guests can browse categories quickly on phone, tablet or desktop."/><div className="mb-8 flex gap-2 overflow-x-auto pb-2">{categories.map((name)=><button key={name} onClick={()=>setCategory(name)} className={`min-h-[44px] rounded-full px-5 font-bold transition ${category===name ? 'bg-[#c87533] text-white' : 'border border-white/10 bg-white/5 text-[#f2dfbd]'}`}>{name}</button>)}</div><div className="grid gap-4 md:grid-cols-2">{urbanBiteConcept.menu[category].map(([name, desc, price, tag])=><article key={name} className="rounded-3xl border border-white/10 bg-white/[0.055] p-5"><div className="flex items-start justify-between gap-4"><h3 className="text-xl font-semibold text-white">{name}</h3><strong className="text-[#d7a85f]">{price}</strong></div><p className="mt-2 leading-7 text-[#d8c7ad]">{desc}</p>{tag && <span className="mt-3 inline-flex rounded-full bg-[#738351]/20 px-3 py-1 text-xs font-bold text-[#cbdc9a]">{tag}</span>}</article>)}</div><button onClick={()=>scrollTo('urbanbite-reservations')} className="mt-8 rounded-full border border-[#d7a85f]/30 px-6 py-4 font-bold text-[#f3d49a] hover:bg-[#d7a85f]/10">Ask About Today’s Specials</button></div></section>

      <ReservationSection />
      <section className="px-4 py-20 sm:px-5"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2"><div><Intro eyebrow="Hours & location" title="Easy to book, easy to find." text="Practical restaurant details are visible and action-oriented."/><div className="space-y-2">{urbanBiteConcept.hours.map(([day,hours])=><p key={day} className="flex justify-between rounded-2xl border border-white/10 bg-white/[0.055] p-4"><span>{day}</span><strong className="text-[#f3d49a]">{hours}</strong></p>)}</div></div><div className="rounded-[2rem] border border-[#d7a85f]/25 bg-[radial-gradient(circle_at_30%_20%,rgba(200,117,51,.25),transparent_16rem),linear-gradient(135deg,#2b1a10,#10120b)] p-6"><div className="grid min-h-96 place-items-center rounded-[1.5rem] border border-white/10 bg-white/5 text-center"><div><MapPin className="mx-auto mb-4 text-[#d7a85f]" size={44}/><h3 className="text-2xl font-semibold text-white">{urbanBiteConcept.location}</h3><p className="mt-3 text-[#d8c7ad]">{urbanBiteConcept.phone} · {urbanBiteConcept.email}</p><div className="mt-6 flex flex-wrap justify-center gap-3"><a href="https://www.google.com/maps/search/24+Bree+Street+Cape+Town" target="_blank" rel="noreferrer" className="rounded-full bg-[#c87533] px-5 py-3 font-bold text-white">Get Directions <ExternalLink className="inline" size={16}/></a><button onClick={()=>clientEnquiry()} className="rounded-full border border-white/15 px-5 py-3 font-bold text-white"><Phone className="inline" size={16}/> Use This Style</button><button onClick={()=>scrollTo('urbanbite-reservations')} className="rounded-full border border-[#d7a85f]/35 px-5 py-3 font-bold text-[#f3d49a]">Book a Table</button></div></div></div></div></div></section>

      <section className="bg-[#fff4df] px-4 py-20 text-[#1a120d] sm:px-5"><div className="mx-auto max-w-7xl"><Intro dark eyebrow="Gallery" title="Atmosphere guests can feel before they arrive." text="Click any image to open a lightbox. Images are illustrative and chosen to support the visual direction."/><div className="columns-1 gap-4 sm:columns-2 lg:columns-3">{urbanBiteConcept.gallery.map((image, index)=><button key={image.src} onClick={()=>setActiveImage(image)} className="group mb-4 block w-full overflow-hidden rounded-[2rem] bg-white text-left shadow-lg"><img src={image.src} alt={image.alt} loading="lazy" decoding="async" className={`${index % 3 === 1 ? 'h-80' : 'h-64'} w-full object-cover transition duration-700 group-hover:scale-105`}/><span className="block px-4 py-3 text-xs text-[#6a5648]">Illustrative image</span></button>)}</div></div></section>

      <section className="px-4 py-20 sm:px-5"><div className="mx-auto max-w-7xl"><div className="rounded-[2.5rem] border border-[#d7a85f]/25 bg-[#d7a85f]/10 p-8 sm:p-12"><Intro eyebrow="Private dining" title="Private tables, special nights, unforgettable food." text="Birthday dinners, corporate dinners, small events, wine evenings and chef’s table experiences can all be presented with dedicated enquiry paths."/><button onClick={()=>scrollTo('urbanbite-reservations')} className="rounded-full bg-[#c87533] px-7 py-4 font-bold text-white">Enquire About Events</button></div></div></section>
      <section className="px-4 pb-20 sm:px-5"><div className="mx-auto max-w-7xl"><Intro eyebrow="Specials" title="Reasons to visit this week." text="Premium promo cards help restaurants market quiet nights and signature offers."/><div className="grid gap-5 lg:grid-cols-3">{urbanBiteConcept.specials.map((s)=><article key={s.title} className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-6"><Clock className="text-[#d7a85f]"/><h3 className="mt-5 text-2xl font-semibold text-white">{s.title}</h3><p className="mt-3 leading-7 text-[#d8c7ad]">{s.text}</p><p className="mt-4 font-bold text-[#f3d49a]">{s.time}</p><button onClick={()=>scrollTo('urbanbite-reservations')} className="mt-5 rounded-full border border-[#d7a85f]/30 px-5 py-3 font-bold text-[#f3d49a]">Enquire</button></article>)}</div></div></section>
      <section className="bg-[#fff4df] px-4 py-20 text-[#1a120d] sm:px-5"><div className="mx-auto max-w-7xl"><Intro dark eyebrow="Reviews" title="Trust signals for confident bookings." text="Realistic testimonials show date nights, family lunches and business dinners."/><div className="grid gap-5 lg:grid-cols-3">{urbanBiteConcept.reviews.map((r)=><article key={r.name} className="rounded-[2rem] bg-white p-6 shadow-xl"><div className="flex gap-1 text-[#c87533]">{Array.from({length:5}).map((_,i)=><Star key={i} size={18} fill="currentColor"/>)}</div><p className="mt-5 leading-8 text-[#5b4638]">“{r.text}”</p><p className="mt-5 font-semibold">{r.name}</p><p className="text-sm text-[#8a4d24]">{r.type}</p></article>)}</div></div></section>
      <section className="px-4 py-20 sm:px-5"><div className="mx-auto max-w-4xl"><Intro eyebrow="FAQ" title="Answers before guests call." text="Accordion content keeps mobile pages tidy while covering common questions."/>{urbanBiteConcept.faqs.map((item,index)=><div key={item.question} className="border-t border-white/10 py-2"><button onClick={()=>setOpenFaq(openFaq===index ? -1 : index)} className="flex w-full items-center justify-between gap-4 py-4 text-left font-semibold text-[#fff6dd]"><span>{item.question}</span><ChevronDown className={`shrink-0 transition ${openFaq===index ? 'rotate-180' : ''}`} /></button>{openFaq===index && <p className="pb-4 leading-7 text-[#d8c7ad]">{item.answer}</p>}</div>)}</div></section>
      <section className="px-4 pb-24 sm:px-5"><div className="mx-auto max-w-5xl rounded-[2.5rem] border border-[#d7a85f]/30 bg-[linear-gradient(135deg,rgba(200,117,51,.28),rgba(255,255,255,.06)),#1a120d] p-8 text-center shadow-2xl sm:p-12"><p className="text-sm uppercase tracking-[0.25em] text-[#f3d49a]">Final CTA</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.04em] text-white sm:text-6xl">Hungry yet?</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-[#eadbc4]">Book your table, explore the menu, or send us a message about private dining.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><button onClick={()=>scrollTo('urbanbite-reservations')} className="rounded-full bg-[#c87533] px-7 py-4 font-bold text-white">Book a Table</button><button onClick={()=>scrollTo('urbanbite-menu')} className="rounded-full border border-white/15 px-7 py-4 font-bold text-white">View Menu</button><a href="https://www.google.com/maps/search/24+Bree+Street+Cape+Town" target="_blank" rel="noreferrer" className="rounded-full border border-[#d7a85f]/35 px-7 py-4 font-bold text-[#f3d49a]">Get Directions</a></div><button onClick={()=>clientEnquiry()} className="mt-5 rounded-full bg-[#fff4df] px-7 py-4 font-bold text-[#1a120d]">I want a restaurant website like this</button><p className="mx-auto mt-6 max-w-3xl rounded-2xl border border-white/10 bg-white/5 p-4 text-sm leading-6 text-[#d8c7ad]">This concept website shows how a business in this industry could be presented online. Images, prices, services, reviews, and business details are illustrative.</p></div></section>
    </main>{activeImage && <Lightbox image={activeImage} onClose={()=>setActiveImage(null)} />}
  </div>;
}

function ReservationSection(){return <section id="urbanbite-reservations" className="bg-[#20150f] px-4 py-20 sm:px-5"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.8fr_1.2fr]"><Intro eyebrow="Reservations" title="Request a table in seconds." text="This is a concept enquiry form showing how reservation requests could be handled."/><form name="project-enquiry" method="POST" action="/" data-netlify="true" className="rounded-[2rem] border border-white/10 bg-white/[0.055] p-5 sm:p-6"><input type="hidden" name="form-name" value="project-enquiry"/><input type="hidden" name="websiteType" value="Restaurant Website"/><input type="hidden" name="budget" value="Example reservation enquiry"/><div className="grid gap-4 md:grid-cols-3"><Field label="Date" name="date" type="date"/><Field label="Time" name="time" type="time"/><Field label="Guests" name="guests" type="number" min="1" placeholder="2"/></div><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label="Name" name="name" required/><Field label="Phone / WhatsApp" name="phone" type="tel"/><Field label="Email" name="email" type="email" required/></div><input type="hidden" name="business" value="UrbanBite Restaurant example reservation"/><label className="mt-4 block text-sm font-medium text-[#d8c7ad]">Special requests<textarea name="message" rows="4" className="input-luxury mt-2 min-h-28 resize-y" defaultValue="Restaurant Website — example reservation enquiry." /></label><button className="premium-button mt-5 rounded-full bg-[#c87533] px-7 py-4 font-bold text-white">Request Reservation</button><p className="mt-4 text-sm text-[#cdbb9c]">This is a concept enquiry form showing how reservation requests could be handled.</p></form></div></section>}
function Field({ label, name, type='text', min, placeholder='', required=false }) { return <label className="block text-sm font-medium text-[#d8c7ad]">{label}<input name={name} type={type} min={min} placeholder={placeholder} required={required} className="input-luxury mt-2 min-h-[52px]" /></label>; }
function Intro({ eyebrow, title, text, dark=false }) { return <div className="mb-10 max-w-3xl"><p className={`text-sm uppercase tracking-[0.25em] ${dark ? 'text-[#a35c2e]' : 'text-[#d7a85f]'}`}>{eyebrow}</p><h2 className={`mt-3 text-4xl font-semibold tracking-[-0.04em] sm:text-5xl ${dark ? 'text-[#1a120d]' : 'text-white'}`}>{title}</h2><p className={`mt-4 text-lg leading-8 ${dark ? 'text-[#6a5648]' : 'text-[#d8c7ad]'}`}>{text}</p></div>; }
function Lightbox({ image, onClose }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/80 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><button onClick={onClose} className="absolute right-5 top-5 grid h-11 w-11 place-items-center rounded-full bg-white/10 text-white"><X /></button><figure className="max-w-5xl"><img src={image.src} alt={image.alt} className="max-h-[82vh] rounded-[2rem] object-contain shadow-2xl"/><figcaption className="mt-3 text-center text-sm text-[#d8c7ad]">{image.alt} · Illustrative image</figcaption></figure></div>; }
