import { useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowUpRight } from 'lucide-react';
import { websiteOptions } from '../data/siteContent';
import SectionHeader from './SectionHeader';
import WebsiteOptionModal from './WebsiteOptionModal';

const enquire = (title) => { window.dispatchEvent(new CustomEvent('select-website-type', { detail: title })); document.getElementById('contact')?.scrollIntoView({ behavior: 'smooth' }); };
export default function WebsiteOptions(){const [selected,setSelected]=useState(null);return <section id="options" className="px-4 py-20 sm:px-5 md:py-28"><div className="mx-auto max-w-7xl"><SectionHeader eyebrow="Website options" title="Choose the kind of website your business needs." text="Explore polished website directions that can be shaped around your industry, content and growth goals."/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{websiteOptions.map((o,i)=><motion.article initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true, margin:'-80px'}} transition={{duration:.55,delay:i*.025}} className="luxury-card luxury-card-hover rounded-[1.75rem] p-5 sm:p-6" key={o.title}><div className="mb-5 h-40 overflow-hidden rounded-[1.4rem] border border-white/10 bg-gradient-to-br from-white/10 via-[#d8b56d]/10 to-transparent p-3"><div className="h-full rounded-2xl bg-[#0b0a08]/50 p-3 transition duration-500 group-hover:scale-[1.02]"><div className="mb-3 h-4 w-20 rounded-full bg-[#d8b56d]/50"/><div className="grid h-[calc(100%-1.75rem)] grid-cols-[.7fr_1fr] gap-3"><div className="rounded-2xl bg-gradient-to-br from-[#d8b56d]/35 to-white/10"/><div className="space-y-2 self-end"><div className="h-3 rounded-full bg-white/20"/><div className="h-3 w-3/4 rounded-full bg-white/10"/><div className="h-8 rounded-2xl bg-[#d8b56d]/25"/></div></div></div></div><h3 className="text-xl font-semibold text-[#fff6dd] sm:text-2xl">{o.title}</h3><p className="mt-3 leading-7 text-[#c9c0ad]">{o.description}</p><p className="mt-4 text-sm text-[#d8b56d]">Best for: {o.bestFor}</p><ul className="mt-4 flex flex-wrap gap-2">{o.features.map(f=><li className="rounded-full bg-white/5 px-3 py-1.5 text-xs text-[#ddd2bc]" key={f}>{f}</li>)}</ul><div className="mt-6 flex flex-col gap-3 sm:flex-row"><button onClick={()=>setSelected(o)} className="inline-flex min-h-[48px] items-center justify-center gap-2 rounded-full border border-white/15 px-5 py-3 font-semibold text-[#fff6dd] transition hover:border-[#d8b56d]/60 hover:bg-white/5">View details <ArrowUpRight size={16}/></button><button onClick={()=>enquire(o.title)} className="premium-button inline-flex min-h-[48px] items-center justify-center rounded-full bg-[#d8b56d] px-5 py-3 font-semibold text-[#17130b] transition hover:-translate-y-0.5">Enquire</button></div></motion.article>)}</div><div className="mt-10 text-center"><a href="#contact" className="inline-flex min-h-[52px] items-center justify-center rounded-full border border-[#d8b56d]/35 bg-white/5 px-7 py-4 font-semibold text-[#f7e8bd] transition hover:-translate-y-0.5 hover:bg-[#d8b56d] hover:text-[#17130b]">Not sure which option fits? Ask us</a></div></div><WebsiteOptionModal option={selected} onClose={()=>setSelected(null)}/></section>}
